import { Link, useForm } from '@inertiajs/react';
import AdminLayout from '../layout';

const statuses = ['COMING_SOON', 'UNLOCKING', 'PREPARING', 'ACTIVE', 'PAUSED'];
export default function CityShow({ city, interestSummary, interests, partnerApplicationSummary, expansionMetrics }: { city: any; interestSummary: any; interests: any; partnerApplicationSummary: any; expansionMetrics: any }) {
    const form = useForm({ status: city.status });
    return <AdminLayout title={city.name}><div className="max-w-xl space-y-4 rounded border border-border p-4">
        <dl className="grid grid-cols-2 gap-3"><dt>Ciudad</dt><dd>{city.name}</dd><dt>Slug</dt><dd>{city.slug}</dd><dt>Estado</dt><dd>{city.status}</dd><dt>País</dt><dd>{city.country_code}</dd><dt>Región</dt><dd>{city.region || '—'}</dd><dt>Prioridad</dt><dd>{city.priority}</dd></dl>
        <Link className="underline" href={`/admin/ciudades/${city.slug}/editar`}>Editar ciudad</Link>
        <form className="flex flex-wrap items-end gap-2" onSubmit={(event) => { event.preventDefault(); form.post(`/admin/ciudades/${city.slug}/estado`); }}><label className="grid gap-1 text-sm">Cambiar estado<select value={form.data.status} onChange={(e) => form.setData('status', e.target.value)}>{statuses.map((status) => <option key={status} value={status}>{status}</option>)}</select></label><button className="rounded border px-3 py-2" disabled={form.processing}>Actualizar estado</button></form>
        <section className="border-t border-border pt-4"><h2 className="font-semibold">INTERESADOS</h2><p className="mt-2 text-2xl font-bold">{interestSummary.total}</p><p className="text-sm text-muted-foreground">{interestSummary.registered} registrados · {interestSummary.guests} visitantes anónimos</p>{interests.data.length ? <div className="mt-4 divide-y divide-border text-sm">{interests.data.map((interest: any) => <div className="py-3" key={interest.id}>{interest.user ? `${interest.user.name} · ${interest.user.email}` : 'Visitante anónimo'}<span className="block text-muted-foreground">{interest.created_at}</span></div>)}</div> : <p className="mt-3 text-sm text-muted-foreground">Aún no hay intereses registrados.</p>}</section>
        <section className="border-t border-border pt-4"><h2 className="font-semibold">SOLICITUDES PARTNER</h2><p className="mt-2 text-2xl font-bold">{partnerApplicationSummary.total}</p><p className="text-sm text-muted-foreground">{partnerApplicationSummary.submitted} enviadas · {partnerApplicationSummary.qualified} calificadas · {partnerApplicationSummary.approved} aprobadas</p></section>
        <section className="border-t border-border pt-4"><h2 className="font-semibold">EXPANSIÓN</h2><div className="mt-3 grid gap-4 text-sm sm:grid-cols-2"><div><h3 className="font-medium">DEMANDA</h3><dl className="mt-1 grid grid-cols-2 gap-1"><dt>Total interesados</dt><dd>{expansionMetrics.interest_total}</dd><dt>Registrados</dt><dd>{expansionMetrics.interest_registered}</dd><dt>Guest</dt><dd>{expansionMetrics.interest_guests}</dd><dt>Última actividad</dt><dd>{expansionMetrics.interest_latest_activity ?? '—'}</dd></dl></div><div><h3 className="font-medium">OFERTA</h3><dl className="mt-1 grid grid-cols-2 gap-1"><dt>Solicitudes partner</dt><dd>{expansionMetrics.application_total}</dd><dt>Submitted</dt><dd>{expansionMetrics.application_submitted}</dd><dt>Contacted</dt><dd>{expansionMetrics.application_contacted}</dd><dt>Qualified</dt><dd>{expansionMetrics.application_qualified}</dd><dt>Approved</dt><dd>{expansionMetrics.application_approved}</dd><dt>Locations reales</dt><dd>{expansionMetrics.location_total}</dd><dt>Partners publicados</dt><dd>{expansionMetrics.published_partner_total}</dd></dl></div></div></section>
    </div></AdminLayout>;
}
