<?php
namespace App\Http\Controllers;
use App\Models\{Benefit,Experience,JpHold,Location,Partner,RewardTransaction,Unlock,UnlockParticipation}; use App\Services\{UnlockParticipationService,UnlockStatusService}; use Illuminate\Http\Request; use Illuminate\Support\Str; use Inertia\Inertia;
class AdminUnlockController extends Controller {
 private function metrics(Unlock $u):array{$m=$u->participations()->selectRaw("count(*) filter(where status='INTERESTED') interested,count(*) filter(where status in('COMMITTED','UNLOCKED_PENDING_CONFIRMATION','CONFIRMED','FULFILLED','NO_SHOW')) committed,count(*) filter(where status='CONFIRMED') confirmed,count(*) filter(where status='FULFILLED') fulfilled,count(*) filter(where status='CANCELLED_ON_TIME') cancelled,count(*) filter(where status='EXPIRED') expired,count(*) filter(where status='NO_SHOW') no_show")->first()->getAttributes();$h=JpHold::whereHas('participation',fn($q)=>$q->where('unlock_id',$u->id))->selectRaw("coalesce(sum(amount) filter(where status='HELD'),0) held,coalesce(sum(amount) filter(where status='RELEASED'),0) released,coalesce(sum(amount) filter(where status='FORFEITED'),0) forfeited")->first();$m+=['jp_held'=>(int)$h->held,'jp_released'=>(int)$h->released,'jp_forfeited'=>(int)$h->forfeited,'jp_bonus_awarded'=>(int)RewardTransaction::whereHas('unlockParticipation',fn($q)=>$q->where('unlock_id',$u->id))->where('source','unlock_fulfillment')->sum('amount')];$m['fulfillment_rate']=$m['committed']?round($m['fulfilled']/$m['committed']*100,1):0;return $m;}
 public function index(){$us=Unlock::with('partner')->latest()->get();$us->each(fn($u)=>$u->setAttribute('metrics',$this->metrics($u)));return Inertia::render('admin/unlocks/index',['unlocks'=>$us]);}
 public function form(?Unlock $unlock=null){return Inertia::render('admin/unlocks/form',['unlock'=>$unlock?->load('locations'),'partners'=>Partner::orderBy('name')->get(['id','name']),'locations'=>Location::orderBy('name')->get(['id','name']),'benefits'=>Benefit::orderBy('title')->get(['id','title']),'experiences'=>Experience::orderBy('title')->get(['id','title'])]);}
 public function save(Request $r,?Unlock $unlock=null){$d=$r->validate($this->rules());$unlock??=new Unlock(['created_by_user_id'=>$r->user()->id]);$unlock->fill($d);$unlock->slug??=Str::slug($d['title']).'-'.Str::lower(Str::random(5));$unlock->save();$unlock->locations()->sync($d['location_ids']??[]);return to_route('admin.unlocks.index');}
 public function transition(Request $r,Unlock $unlock,UnlockStatusService $s){$d=$r->validate(['status'=>'required|in:APPROVED,SCHEDULED,ACTIVE,CANCELLED,REJECTED','reason'=>'nullable|string']);$s->transition($unlock,$d['status'],$r->user(),$d['reason']??null);return back();}
 public function fulfill(Request $r,Unlock $unlock,UnlockParticipation $p,UnlockParticipationService $s){abort_unless($p->unlock_id===$unlock->id,404);$d=$r->validate(['reason'=>'required|string|max:2000']);$s->fulfill($p,$r->user(),'admin_manual',$d['reason'],null,true);return back();}
 private function rules():array{return ['title'=>'required|string|max:255','partner_id'=>'nullable|exists:partners,id','origin'=>'required|in:JAKAWI,PARTNER','type'=>'required|in:BENEFIT,PRICE,EXPERIENCE,SECRET','minimum_commitments'=>'required|integer|min:1','maximum_capacity'=>'nullable|integer|min:1','commitment_deadline'=>'nullable|date','confirmation_deadline'=>'nullable|date','fulfillment_starts_at'=>'nullable|date','fulfillment_ends_at'=>'nullable|date','free_user_eligible'=>'boolean','member_eligible'=>'boolean','jp_deposit'=>'nullable|integer|min:0','jp_completion_bonus'=>'nullable|integer|min:0','linked_benefit_id'=>'nullable|exists:benefits,id','linked_experience_id'=>'nullable|exists:experiences,id','location_ids'=>'array'];}
}
