<?php
namespace App\Http\Controllers;
use App\Models\Unlock; use App\Models\UnlockParticipation; use App\Services\AnalyticsTracker; use App\Services\JpBalanceService; use App\Services\UnlockParticipationService; use Illuminate\Http\Request; use Inertia\Inertia;
class UnlockController extends Controller {
 public function show(Request $request,Unlock $unlock,AnalyticsTracker $analytics){abort_unless(in_array($unlock->status,[Unlock::ACTIVE,Unlock::GOAL_REACHED],true),404);$unlock->load(['partner','locations']);$analytics->unlock($unlock,'unlock_viewed');return Inertia::render('unlocks/show',['unlock'=>$this->data($unlock,true),'participation'=>$request->user()?->unlockParticipations()->where('unlock_id',$unlock->id)->first()?->only(['status','interested_at','committed_at']),'jpBalance'=>$request->user()?app(JpBalanceService::class)->for($request->user()):null]);}
 public function interest(Request $request,Unlock $unlock,UnlockParticipationService $service,AnalyticsTracker $analytics){$service->interest($unlock,$request->user());$analytics->unlock($unlock,'unlock_interested');return back();}
 public function commit(Request $request,Unlock $unlock,UnlockParticipationService $service,AnalyticsTracker $analytics){$analytics->unlock($unlock,'unlock_commitment_started');$service->commit($unlock,$request->user());$analytics->unlock($unlock,'unlock_committed');return back();}
 public function cancel(Request $request,Unlock $unlock,UnlockParticipationService $service,AnalyticsTracker $analytics){$service->cancel($unlock,$request->user());$analytics->unlock($unlock,'unlock_commitment_cancelled');return back();}
 public function share(Request $request,Unlock $unlock,AnalyticsTracker $analytics){$analytics->unlock($unlock,'unlock_shared');return response()->noContent();}
 public function data(Unlock $u,bool $detail=false):array {$count=$u->committedCount();$reveal=$u->revealable();$hiddenPartner=$u->secret_mode&&$u->hide_partner_until_unlock&&!$reveal;$hiddenLocation=$u->secret_mode&&$u->hide_location_until_unlock&&!$reveal;$hiddenOffer=$u->secret_mode&&$u->hide_exact_offer_until_unlock&&!$reveal;return ['id'=>$u->id,'slug'=>$u->slug,'title'=>$u->title,'short_description'=>$u->short_description,'description'=>$detail&&!$hiddenOffer?$u->description:null,'terms'=>$detail?$u->terms:null,'type'=>$u->type,'status'=>$u->status,'minimum_commitments'=>$u->minimum_commitments,'maximum_capacity'=>$u->maximum_capacity,'committed_count'=>$count,'remaining'=>max(0,$u->minimum_commitments-$count),'is_full'=>$u->maximum_capacity!==null&&$count>=$u->maximum_capacity,'commitment_deadline'=>$u->commitment_deadline,'free_user_eligible'=>$u->free_user_eligible,'member_eligible'=>$u->member_eligible,'free_user_offer'=>$hiddenOffer?null:$u->free_user_offer,'member_offer'=>$hiddenOffer?null:$u->member_offer,'jp_deposit'=>$u->jp_deposit,'featured'=>$u->featured,'secret_mode'=>$u->secret_mode,'partner'=>$hiddenPartner?null:$u->partner?->only(['name','slug']),'locations'=>$hiddenLocation?[]:$u->locations->map->only(['name','slug','city']),'revealable'=>$reveal];}
}
