<?php
namespace App\Http\Controllers;
use App\Models\Unlock; use App\Models\UnlockParticipation; use App\Services\AnalyticsTracker; use App\Services\JpBalanceService; use App\Services\ReferralCodeService; use App\Services\UnlockParticipationService; use Illuminate\Http\Request; use Inertia\Inertia;
class UnlockController extends Controller {
 public function show(Request $request,Unlock $unlock,AnalyticsTracker $analytics){abort_unless(in_array($unlock->status,[Unlock::ACTIVE,Unlock::GOAL_REACHED,Unlock::UNLOCKED],true),404);$unlock->load(['partner','locations']);$analytics->resetJourneyIntent($unlock);$analytics->unlock($unlock,'unlock_viewed');$membership=$request->user()?->hasActiveMembership()??false;$participation=$request->user()?->unlockParticipations()->where('unlock_id',$unlock->id)->first();$available=$unlock->status===Unlock::ACTIVE&&($unlock->commitment_deadline===null||$unlock->commitment_deadline->isFuture())&&($unlock->maximum_capacity===null||$unlock->committedCount()<$unlock->maximum_capacity);if($request->user()&&!$membership&&!$unlock->free_user_eligible&&$unlock->member_eligible&&$available&&($participation===null||in_array($participation->status,[UnlockParticipation::INTERESTED,UnlockParticipation::WAITLISTED],true))){$analytics->journeyMembershipGateViewed($unlock);}return Inertia::render('unlocks/show',['unlock'=>$this->data($unlock,true),'participation'=>$participation?->only(['status','interested_at','committed_at','confirmation_requested_at','confirmed_at','fulfilled_at','no_show_at']),'hasActiveMembership'=>$membership,'jpBalance'=>$request->user()?app(JpBalanceService::class)->for($request->user()):null]);}
 public function interest(Request $request,Unlock $unlock,UnlockParticipationService $service,AnalyticsTracker $analytics){$service->interest($unlock,$request->user());$analytics->unlock($unlock,'unlock_interested');return back();}
 public function commit(Request $request,Unlock $unlock,UnlockParticipationService $service,AnalyticsTracker $analytics){$analytics->journeyIntentStarted($unlock);if(!$request->user()->hasActiveMembership()&&!$unlock->free_user_eligible&&$unlock->member_eligible){return redirect('/membresia?'.http_build_query(['journey'=>'UNLOCK','action'=>'COMMIT','resource_id'=>$unlock->id]));}$analytics->unlock($unlock,'unlock_commitment_started');$service->commit($unlock,$request->user());$analytics->unlock($unlock,'unlock_committed');return back();}
 public function cancel(Request $request,Unlock $unlock,UnlockParticipationService $service,AnalyticsTracker $analytics){$service->cancel($unlock,$request->user());$analytics->unlock($unlock,'unlock_commitment_cancelled');return back();}
 public function confirm(Request $request,Unlock $unlock,UnlockParticipationService $service,AnalyticsTracker $analytics){$service->confirm($unlock,$request->user());$analytics->unlock($unlock,'unlock_confirmed');return back();}
 public function share(Request $request,Unlock $unlock,AnalyticsTracker $analytics,ReferralCodeService $codes){$analytics->unlock($unlock,'unlock_shared');$url=route('unlocks.show',$unlock);if($request->user())$url=route('referrals.unlock',['code'=>$codes->ensureFor($request->user()),'unlock'=>$unlock]);return response()->json(['url'=>$url]);}
 public function data(Unlock $u,bool $detail=false):array {$count=$u->committedCount();$reveal=$u->revealable();$hiddenPartner=$u->secret_mode&&$u->hide_partner_until_unlock&&!$reveal;$hiddenLocation=$u->secret_mode&&$u->hide_location_until_unlock&&!$reveal;$hiddenOffer=$u->secret_mode&&$u->hide_exact_offer_until_unlock&&!$reveal;return ['id'=>$u->id,'slug'=>$u->slug,'destination_url'=>app(\App\Services\ProductLandingResolver::class)->navigationUrl($u, auth()->check()),'title'=>$u->title,'short_description'=>$u->short_description,'description'=>$detail&&!$hiddenOffer?$u->description:null,'terms'=>$detail?$u->terms:null,'type'=>$u->type,'status'=>$u->status,'minimum_commitments'=>$u->minimum_commitments,'maximum_capacity'=>$u->maximum_capacity,'committed_count'=>$count,'remaining'=>max(0,$u->minimum_commitments-$count),'is_full'=>$u->maximum_capacity!==null&&$count>=$u->maximum_capacity,'commitment_deadline'=>$u->commitment_deadline,'confirmation_deadline'=>$u->confirmation_deadline,'fulfillment_starts_at'=>$u->fulfillment_starts_at,'fulfillment_ends_at'=>$u->fulfillment_ends_at,'free_user_eligible'=>$u->free_user_eligible,'member_eligible'=>$u->member_eligible,'free_user_offer'=>$hiddenOffer?null:$u->free_user_offer,'member_offer'=>$hiddenOffer?null:$u->member_offer,'jp_deposit'=>$u->jp_deposit,'jp_completion_bonus'=>$u->jp_completion_bonus,'featured'=>$u->featured,'secret_mode'=>$u->secret_mode,'partner'=>$hiddenPartner?null:$u->partner?->only(['name','slug']),'locations'=>$hiddenLocation?[]:$u->locations->map->only(['name','slug','city']),'revealable'=>$reveal];}
}
