import { Head, router } from '@inertiajs/react';
import { Search } from 'lucide-react';
import { useState } from 'react';
import BenefitCard from '@/components/benefit-card';
import ExperienceCard from '@/components/experience-card';
import MobileBottomNav from '@/components/mobile-bottom-nav';
import type { BenefitSummary } from '@/types';
type Experience = { id: number; slug: string; title: string; image_url?: string | null; category?: string | null; sessions?: Array<{ starts_at?: string; venue_label?: string | null; location?: { name?: string } | null }> };
const categories = [['todos', 'Todos'], ['comer', 'Comer'], ['cafe', 'Café'], ['fitness', 'Fitness'], ['bienestar', 'Bienestar'], ['salir', 'Salir'], ['experiences', 'Experiencias']];
export default function Explore({ query = '', category, type, benefits = [], experiences = [] }: { query?: string; category?: string | null; type?: string | null; benefits?: BenefitSummary[]; experiences?: Experience[] }) { const [value, setValue] = useState(query); const visit = (next: Record<string, string>) => router.get('/explorar', { q: value, category: category ?? 'todos', type: type ?? '', ...next }, { preserveState: true, replace: true }); return <><Head title="Explorar" /><main className="min-h-screen bg-background pb-28 text-foreground"><section className="mx-auto w-full max-w-5xl px-4 pt-[max(2rem,env(safe-area-inset-top))] sm:px-6"><p className="text-sm font-semibold tracking-wide text-brand uppercase">Descubre</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">EXPLORA COCHABAMBA</h1><form onSubmit={e => { e.preventDefault(); visit({}); }} className="relative mt-6"><Search className="pointer-events-none absolute left-4 top-1/2 size-5 -translate-y-1/2 text-muted-foreground" /><input value={value} onChange={e => setValue(e.target.value)} placeholder="¿Qué quieres hacer?" className="min-h-13 w-full rounded-2xl border border-border bg-surface py-3 pr-4 pl-12 text-base outline-none focus-visible:ring-2 focus-visible:ring-brand" /></form><div className="mt-5 flex gap-2 overflow-x-auto pb-2">{categories.map(([key, label]) => <button key={key} onClick={() => visit({ category: key })} className={`min-h-11 shrink-0 rounded-full border px-4 text-sm font-semibold ${String(category ?? 'todos') === key ? 'border-brand bg-brand text-brand-foreground' : 'border-border bg-surface'}`}>{label}</button>)}</div><div className="mt-3 flex gap-3 text-sm font-semibold"><button onClick={() => visit({ type: '' })} className={type ? 'text-muted-foreground' : 'text-brand'}>Todo</button><button onClick={() => visit({ type: 'benefits' })} className={type === 'benefits' ? 'text-brand' : 'text-muted-foreground'}>Beneficios</button><button onClick={() => visit({ type: 'experiences' })} className={type === 'experiences' ? 'text-brand' : 'text-muted-foreground'}>Experiencias</button></div>{benefits.length || experiences.length ? <div className="mt-7 space-y-10">{benefits.length ? <section><h2 className="text-xl font-bold">Beneficios</h2><div className="mt-4 grid gap-4 sm:grid-cols-3">{benefits.map(item => <BenefitCard key={item.id} benefit={item} />)}</div></section> : null}{experiences.length ? <section><h2 className="text-xl font-bold">Experiencias</h2><div className="mt-4 grid gap-4 sm:grid-cols-3">{experiences.map(item => <ExperienceCard key={item.id} experience={item} />)}</div></section> : null}</div> : <div className="mt-12 rounded-[22px] border border-border bg-surface p-7 text-center"><h2 className="text-xl font-bold">Todavía no hay resultados</h2><p className="mt-2 text-sm text-muted-foreground">Prueba otra búsqueda o vuelve pronto a descubrir novedades.</p></div>}</section></main><MobileBottomNav /></>; }
