import { Head, Link, router } from '@inertiajs/react';
import { Search } from 'lucide-react';
import { useState } from 'react';
import BenefitCard from '@/components/benefit-card';
import ExperienceCard from '@/components/experience-card';
import { JakawiImage } from '@/components/jakawi-image';
import { EmptyState } from '@/components/state-panel';
import type { BenefitSummary } from '@/types';

type Experience = { id: number; slug: string; title: string; image_url?: string | null; image_srcset?: Array<{ src: string; width: number }>; category?: string | null; sessions?: Array<{ starts_at?: string; venue_label?: string | null; location?: { name?: string } | null }> };
type Partner = { id: number; slug: string; name: string; category?: string | null; description?: string | null; cover_url?: string | null; cover_srcset?: Array<{ src: string; width: number }> };
type Result = (BenefitSummary & { result_type: 'benefit' }) | (Experience & { result_type: 'experience' }) | (Partner & { result_type: 'partner' });
const categories = [['todos', 'Todo'], ['food', 'Comer'], ['cafe', 'Café'], ['fitness', 'Fitness'], ['nightlife', 'Salir'], ['wellness', 'Bienestar'], ['experiences', 'Experiencias']];

function PartnerResult({ partner }: { partner: Partner }) {
    return <Link href={`/partners/${partner.slug}`} className="group grid min-h-28 grid-cols-[104px_1fr] overflow-hidden rounded-2xl bg-surface-elevated transition active:scale-[.99] sm:grid-cols-[180px_1fr]"><div className="bg-surface-muted"><JakawiImage src={partner.cover_url} srcset={partner.cover_srcset} sizes="180px" alt={partner.name} className="h-full w-full object-cover" /></div><div className="flex min-w-0 flex-col justify-center p-4"><p className="text-xs font-extrabold tracking-[0.12em] text-brand uppercase">Lugar</p><h2 className="mt-1 text-xl font-extrabold">{partner.name}</h2>{partner.category ? <p className="mt-1 text-sm text-muted-foreground">{partner.category}</p> : null}{partner.description ? <p className="mt-2 line-clamp-1 text-sm text-muted-foreground">{partner.description}</p> : null}</div></Link>;
}

export default function Explore({ query = '', category, type, results = [] }: { query?: string; category?: string | null; type?: string | null; results?: Result[] }) {
    const [value, setValue] = useState(query);
    const visit = (next: Record<string, string>) => router.get('/explorar', { q: value, category: category ?? 'todos', type: type ?? '', ...next }, { preserveState: true, replace: true });
    const hasFilters = value !== '' || (category && category !== 'todos') || type;
    return <><Head title="Explorar" /><main className="min-h-screen bg-background pb-28 text-foreground"><section className="mx-auto w-full max-w-5xl px-4 pt-[max(2rem,env(safe-area-inset-top))] sm:px-6"><p className="text-sm font-bold tracking-[0.12em] text-brand uppercase">Descubre</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">EXPLORA COCHABAMBA</h1><form onSubmit={event => { event.preventDefault(); visit({}); }} className="relative mt-6"><Search className="pointer-events-none absolute left-4 top-1/2 size-5 -translate-y-1/2 text-muted-foreground" /><input value={value} onChange={event => setValue(event.target.value)} placeholder="¿Qué quieres hacer?" className="min-h-13 w-full rounded-2xl border border-border bg-surface py-3 pr-4 pl-12 text-base outline-none focus-visible:ring-2 focus-visible:ring-brand" /></form><div className="mt-5 flex gap-2 overflow-x-auto pb-2">{categories.map(([key, label]) => <button type="button" key={key} onClick={() => visit({ category: key })} className={`min-h-11 shrink-0 rounded-full border px-4 text-sm font-semibold ${String(category ?? 'todos') === key ? 'border-brand bg-brand text-brand-foreground' : 'border-border bg-surface'}`}>{label}</button>)}</div><div className="mt-3 flex gap-4 text-sm font-semibold"><button type="button" onClick={() => visit({ type: '' })} className={type ? 'text-muted-foreground' : 'text-brand'}>Todo</button><button type="button" onClick={() => visit({ type: 'benefits' })} className={type === 'benefits' ? 'text-brand' : 'text-muted-foreground'}>Beneficios</button><button type="button" onClick={() => visit({ type: 'experiences' })} className={type === 'experiences' ? 'text-brand' : 'text-muted-foreground'}>Experiencias</button></div>{results.length ? <section className="mt-7"><p className="text-sm font-semibold text-muted-foreground">{results.length} resultados para descubrir</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{results.map(result => result.result_type === 'partner' ? <PartnerResult key={`partner-${result.id}`} partner={result} /> : result.result_type === 'benefit' ? <div key={`benefit-${result.id}`}><p className="mb-2 text-xs font-extrabold tracking-[0.12em] text-brand uppercase">Beneficio</p><BenefitCard benefit={result} /></div> : <div key={`experience-${result.id}`}><p className="mb-2 text-xs font-extrabold tracking-[0.12em] text-brand uppercase">Experiencia</p><ExperienceCard experience={result} /></div>)}</div></section> : <EmptyState className="mt-12" title="NO ENCONTRAMOS ESO" description="Prueba otra búsqueda o cambia los filtros." action={hasFilters ? <button type="button" onClick={() => { setValue(''); router.get('/explorar'); }} className="min-h-11 rounded-xl bg-brand px-4 text-sm font-extrabold text-brand-foreground">LIMPIAR FILTROS</button> : undefined} />}</section></main></>;
}
