import { Head, Link } from '@inertiajs/react';
import { Check, ChevronRight, Sparkles } from 'lucide-react';

type Membership = { id: number; status: string; starts_at: string; ends_at: string; is_active: boolean; amount_paid: string; confirmed_savings: string; remaining_to_payback: string; has_paid_for_itself: boolean };
type MembershipConfig = { price_bob: number; duration_days: number };
type Activity = { id: string; type: 'redemption' | 'experience'; title: string; detail: string | null; savings_amount?: string; happened_at: string };
type Benefit = { slug: string; title: string; partner_name: string };

function formatDate(value: string) { return new Intl.DateTimeFormat('es-BO', { dateStyle: 'medium' }).format(new Date(value)); }
function money(value: string | number) { return Number(value).toFixed(2); }

export default function MiJakawi({ membership, membershipConfig, valueStats, activity, featuredBenefits }: { membership: Membership | null; membershipConfig: MembershipConfig; valueStats: { benefits_used: number; experiences_lived: number }; activity: Activity[]; featuredBenefits: Benefit[] }) {
    if (!membership) return <FreeAccount membershipConfig={membershipConfig} featuredBenefits={featuredBenefits} />;

    const savings = Number(membership.confirmed_savings);
    const amountPaid = Number(membership.amount_paid);
    const isPaidBack = membership.has_paid_for_itself;

    return <><Head title="Mi JAKAWI" /><main className="min-h-screen bg-background px-4 pt-[max(2rem,env(safe-area-inset-top))] pb-28 text-foreground sm:px-6"><section className="mx-auto w-full max-w-xl"><p className="text-sm font-extrabold tracking-[0.14em] text-brand uppercase">MI JAKAWI</p><MembershipCard membership={membership} />
        <section className={isPaidBack ? 'mt-7 rounded-[24px] bg-success-surface p-6' : 'mt-7 border-y border-border py-6'}>
            <p className="text-xs font-extrabold tracking-[0.12em] uppercase">AHORRO ACUMULADO</p>
            <p className="mt-2 text-5xl font-extrabold tracking-[-0.05em]">Bs {money(membership.confirmed_savings)}</p><p className="mt-1 text-sm font-bold text-success">AHORRADOS</p>
            {isPaidBack ? <div className="mt-6"><p className="flex items-center gap-2 text-2xl font-extrabold"><span className="grid size-6 place-items-center rounded-full bg-success text-success-foreground"><Check className="size-4 stroke-[3]" /></span> YA SE PAGÓ SOLA</p><p className="mt-2 leading-6 text-muted-foreground">Pagaste Bs {money(membership.amount_paid)}. Ya ahorraste Bs {money(membership.confirmed_savings)}.</p></div>
                : <div className="mt-6"><p className="text-sm leading-6 text-muted-foreground">{savings === 0 ? 'Empieza a aprovechar tu JAKAWI.' : `Te faltan Bs ${money(membership.remaining_to_payback)} para que tu JAKAWI se pague sola.`}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-surface-muted"><div className="h-full rounded-full bg-brand" style={{ width: `${Math.min(100, Math.max(0, savings / amountPaid * 100))}%` }} /></div></div>}
        </section>
        <section className="mt-8 flex gap-8 border-b border-border pb-7"><Metric value={valueStats.benefits_used} label="beneficios utilizados" /><Metric value={valueStats.experiences_lived} label="experiencias vividas" /></section>
        <ActivityList activity={activity} />
        {!membership.is_active && <section className="mt-8 border-t border-border pt-6"><p className="text-lg font-extrabold">Tu valor sigue aquí.</p><p className="mt-2 leading-6 text-muted-foreground">Explora nuevos beneficios mientras decides cuándo volver a activar tu membresía.</p><Link href="/explorar" className="mt-4 inline-flex min-h-11 items-center gap-2 text-sm font-extrabold text-brand">EXPLORAR <ChevronRight className="size-4" /></Link></section>}
    </section></main></>;
}

function MembershipCard({ membership }: { membership: Membership }) {
    return <section className="mt-5 overflow-hidden rounded-[28px] bg-foreground p-6 text-background"><p className="text-sm font-extrabold tracking-[0.14em] text-background/65 uppercase">JAKAWI</p><p className="mt-3 text-2xl font-extrabold">Vive más. Gasta menos.</p><div className="mt-7 flex items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[0.1em] text-background/65 uppercase">{membership.is_active ? 'Membresía activa' : 'Membresía vencida'}</p><p className="mt-1 font-bold">Hasta {formatDate(membership.ends_at)}</p></div><p className={membership.is_active ? 'rounded-full bg-success px-3 py-1.5 text-xs font-extrabold text-success-foreground' : 'rounded-full bg-surface-muted px-3 py-1.5 text-xs font-extrabold text-foreground'}>{membership.is_active ? 'ACTIVO' : 'VENCIDA'}</p></div></section>;
}

function Metric({ value, label }: { value: number; label: string }) { return <div><p className="text-2xl font-extrabold">{value}</p><p className="mt-1 text-xs font-bold leading-4 text-muted-foreground">{label}</p></div>; }

function ActivityList({ activity }: { activity: Activity[] }) { return <section className="mt-9"><h2 className="text-2xl font-extrabold">TU ACTIVIDAD</h2>{activity.length ? <div className="mt-3 divide-y divide-border">{activity.map(item => <div key={item.id} className="flex items-center justify-between gap-4 py-4"><div className="min-w-0"><p className="truncate font-extrabold">{item.title}</p><p className="mt-1 text-sm text-muted-foreground">{item.detail}{item.detail ? ' · ' : ''}{formatDate(item.happened_at)}</p></div>{item.type === 'redemption' && item.savings_amount ? <p className="shrink-0 text-sm font-extrabold text-success">+Bs {money(item.savings_amount)} ahorrados</p> : <p className="shrink-0 text-sm font-extrabold text-success">VIVIDA</p>}</div>)}</div> : <div className="mt-4 border-l-2 border-brand pl-4"><p className="font-extrabold">Tu primera experiencia JAKAWI empieza aquí.</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Cuando recibas un beneficio confirmado, tu valor aparecerá aquí.</p><Link href="/explorar" className="mt-4 inline-flex min-h-11 items-center gap-2 text-sm font-extrabold text-brand">EXPLORAR <ChevronRight className="size-4" /></Link></div>}</section>; }

function FreeAccount({ membershipConfig, featuredBenefits }: { membershipConfig: MembershipConfig; featuredBenefits: Benefit[] }) { return <><Head title="Mi JAKAWI" /><main className="min-h-screen bg-background px-4 pt-[max(2rem,env(safe-area-inset-top))] pb-28 text-foreground sm:px-6"><section className="mx-auto w-full max-w-xl"><p className="text-sm font-extrabold tracking-[0.14em] text-brand uppercase">MI JAKAWI</p><h1 className="mt-3 text-3xl font-extrabold">Cuenta gratuita</h1><section className="mt-7 overflow-hidden rounded-[28px] bg-foreground p-6 text-background"><Sparkles className="size-7 text-action" /><p className="mt-6 text-sm font-extrabold tracking-[0.14em] text-background/65 uppercase">DESBLOQUEA TU JAKAWI</p><h2 className="mt-2 text-3xl font-extrabold">Más razones para salir.</h2><p className="mt-3 max-w-sm leading-6 text-background/75">Obtén acceso a beneficios y experiencias durante {membershipConfig.duration_days} días.</p><p className="mt-5 text-lg font-extrabold">Bs {money(membershipConfig.price_bob)} <span className="text-sm text-background/65">/ {membershipConfig.duration_days} días</span></p><Link href="/explorar" className="mt-7 inline-flex min-h-13 w-full items-center justify-center gap-2 rounded-2xl bg-brand px-5 text-sm font-extrabold text-brand-foreground">EXPLORAR BENEFICIOS <ChevronRight className="size-4" /></Link></section>{featuredBenefits.length ? <section className="mt-8"><h2 className="text-xl font-extrabold">LO QUE TE ESPERA</h2><div className="mt-3 divide-y divide-border">{featuredBenefits.map(benefit => <Link key={benefit.slug} href={`/beneficios/${benefit.slug}`} className="block py-4"><p className="font-extrabold">{benefit.title}</p><p className="mt-1 text-sm text-muted-foreground">{benefit.partner_name}</p></Link>)}</div></section> : null}</section></main></>; }
