import { Head, Link, usePage } from '@inertiajs/react';
import { Coffee, Dumbbell, HeartPulse, Search, Utensils, Wine } from 'lucide-react';
import { BrandEnergy } from '@/components/brand-energy';
import { CitySelector } from '@/components/city-selector';
import { JakawiImage } from '@/components/jakawi-image';
import ThemeToggle from '@/components/theme-toggle';
import type { DiscoveryOpportunity, HomeDiscovery } from '@/types/discovery';

type MembershipSummary = { confirmed_savings: string; remaining_to_payback: string; has_paid_for_itself: boolean };
type HomeProps = { discovery: HomeDiscovery; myJakawi?: MembershipSummary | null };

function greeting(name?: string) { const hour = new Date().getHours(); return `${hour < 12 ? 'Buenos días' : hour < 19 ? 'Buenas tardes' : 'Buenas noches'}${name ? `, ${name.split(' ')[0]}` : ''}`; }
function SectionHeader({ title, subtitle }: { title: string; subtitle?: string }) { return <div className="px-4 sm:px-0"><h2 className="text-2xl font-bold tracking-tight">{title}</h2>{subtitle ? <p className="mt-1 text-sm text-muted-foreground">{subtitle}</p> : null}</div>; }
export function opportunityLabel(type: DiscoveryOpportunity['type']) { return type === 'BENEFIT' ? 'VER BENEFICIO' : type === 'EXPERIENCE' ? 'VER EXPERIENCIA' : 'VER DESBLOQUEO'; }
function opportunityType(type: DiscoveryOpportunity['type']) { return type === 'BENEFIT' ? 'Beneficio' : type === 'EXPERIENCE' ? 'Experiencia' : 'Desbloqueo'; }
function OpportunityCard({ opportunity }: { opportunity: DiscoveryOpportunity }) { const value = opportunity.primary_value ?? opportunity.secondary_value; return <Link href={opportunity.destination_url} className="block min-w-64 rounded-[var(--radius-card)] border border-border bg-surface p-4"><p className="discovery-eyebrow text-brand">{opportunityType(opportunity.type)}</p><h3 className="mt-2 font-extrabold">{opportunity.title}</h3>{value ? <p className="mt-2 text-sm font-bold">{value}</p> : null}{opportunity.subtitle ? <p className="mt-1 text-sm text-muted-foreground">{opportunity.subtitle}</p> : null}<span className="mt-4 inline-block text-xs font-extrabold tracking-wide text-brand">{opportunityLabel(opportunity.type)}</span></Link>; }
function OpportunitySection({ title, subtitle, opportunities }: { title: string; subtitle?: string; opportunities: DiscoveryOpportunity[] }) { if (!opportunities.length) return null; return <section className="mt-[var(--space-section)]"><SectionHeader title={title} subtitle={subtitle} /><div className="mt-4 flex gap-4 overflow-x-auto px-4 pb-2 [scrollbar-width:none] sm:grid sm:grid-cols-3 sm:px-0">{opportunities.map(opportunity => <OpportunityCard key={`${opportunity.type}-${opportunity.source_id}`} opportunity={opportunity} />)}</div></section>; }
const categories = [{ label: 'Comer', key: 'food', icon: Utensils }, { label: 'Café', key: 'cafe', icon: Coffee }, { label: 'Entrenar', key: 'fitness', icon: Dumbbell }, { label: 'Salir', key: 'nightlife', icon: Wine }, { label: 'Bienestar', key: 'wellness', icon: HeartPulse }];

export default function Welcome({ discovery, myJakawi }: HomeProps) {
 const { auth } = usePage().props; const name = auth.user?.name; const hero = discovery.hero; const heroValue = hero?.primary_value ?? hero?.secondary_value;
 return <><Head title="JAKAWI" /><main className="min-h-screen overflow-hidden bg-background pb-28 font-discovery text-foreground"><section className="mx-auto w-full max-w-5xl pt-[max(2rem,env(safe-area-inset-top))] sm:px-6"><header className="px-4 sm:px-0"><div className="flex items-center justify-between gap-4"><div><CitySelector /><p className="mt-1 text-sm text-muted-foreground">{greeting(name)}</p></div><ThemeToggle /></div><h1 className="mt-4 max-w-xl text-[34px] leading-[1.02] font-extrabold tracking-tight sm:text-5xl">¿QUÉ HACEMOS HOY?</h1><BrandEnergy className="mt-3" /><p className="mt-4 max-w-lg text-base leading-6 text-muted-foreground">{auth.user ? 'Planes, lugares y beneficios pensados para que salgas más.' : 'Descubre nuevas razones para salir, probar y volver a tu ciudad.'}</p><Link href="/explorar" className="relative mt-6 flex min-h-13 items-center rounded-2xl border border-border bg-surface px-12 text-sm text-muted-foreground"><Search className="absolute left-4 size-5" />Buscar lugares, planes o experiencias</Link></header>
 <div className="mt-6 flex gap-3 overflow-x-auto px-4 pb-1 sm:px-0">{categories.map(({ label, key, icon: Icon }) => <Link key={key} href={`/explorar?category=${key}`} className="flex min-h-16 min-w-16 shrink-0 flex-col items-center justify-center gap-1 rounded-2xl border border-border bg-surface px-3 text-xs font-bold"><Icon className="size-5 text-brand" />{label}</Link>)}<Link href="/explorar" className="flex min-h-16 min-w-16 shrink-0 flex-col items-center justify-center gap-1 rounded-2xl border border-border bg-surface px-3 text-xs font-bold">Más</Link></div>
 {hero ? <section className="mx-4 mt-7 overflow-hidden rounded-[var(--radius-card)] border border-border bg-surface-elevated sm:mx-0"><Link href={hero.destination_url} className="block"><div className="relative aspect-[16/10]"><JakawiImage src={hero.image} sizes="(min-width: 1024px) 960px, 100vw" alt={hero.title} className="h-full w-full object-cover" loading="eager" priority fallbackContent={false} />{hero.image ? <div aria-hidden="true" className="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-foreground/75 to-transparent" /> : null}<div className={`absolute inset-x-0 bottom-0 p-5 ${hero.image ? 'text-background' : 'text-foreground'}`}><p className="discovery-eyebrow opacity-85">{opportunityType(hero.type)} · {hero.partner?.name ?? 'JAKAWI'}</p><h2 className="mt-2 max-w-lg text-2xl leading-tight font-extrabold">{hero.title}</h2>{heroValue ? <p className="mt-2 text-sm font-bold">{heroValue}</p> : null}<span className="discovery-primary-action mt-4">{opportunityLabel(hero.type)}</span></div></div></Link></section> : null}
 {myJakawi ? <div className={`mx-4 mt-8 rounded-[20px] p-4 sm:mx-0 ${myJakawi.has_paid_for_itself ? 'bg-success text-success-foreground' : 'bg-surface-muted text-foreground'}`}><p className="text-sm font-bold">{myJakawi.has_paid_for_itself ? 'Tu JAKAWI ya se pagó solo' : `Te faltan Bs ${myJakawi.remaining_to_payback} para que tu JAKAWI se pague solo`}</p><p className="mt-1 text-sm opacity-75">Has ahorrado Bs {myJakawi.confirmed_savings}</p></div> : null}
 <OpportunitySection title="PARA TI" subtitle="Oportunidades para disfrutar más tu ciudad." opportunities={discovery.forYou} /><OpportunitySection title="ESTÁ PASANDO AHORA" opportunities={discovery.happeningNow} /><OpportunitySection title="DESCUBRE MÁS" opportunities={discovery.discoverMore} /></section></main></>;
}
