import { Head, Link, usePage } from '@inertiajs/react';
import { Coffee, Dumbbell, Search, Sparkles, Utensils, Wine } from 'lucide-react';
import BenefitCard from '@/components/benefit-card';
import ExperienceCard from '@/components/experience-card';
import ThemeToggle from '@/components/theme-toggle';
import type { BenefitSummary } from '@/types';
type Experience = { id: number; slug: string; title: string; image_url?: string | null; category?: string | null; sessions?: Array<{ starts_at?: string; venue_label?: string | null; location?: { name?: string } | null }> };
type MembershipSummary = { confirmed_savings: string; remaining_to_payback: string; has_paid_for_itself: boolean };
function greeting(name?: string) { const hour = new Date().getHours(); return `${hour < 12 ? 'Buenos días' : hour < 19 ? 'Buenas tardes' : 'Buenas noches'}${name ? `, ${name.split(' ')[0]}` : ''}`; }
function SectionHeader({ title, subtitle, href }: { title: string; subtitle?: string | null; href: string }) { return <div className="flex items-end justify-between gap-3 px-4 sm:px-0"><div><h2 className="text-2xl font-bold tracking-tight">{title}</h2>{subtitle ? <p className="mt-1 text-sm text-muted-foreground">{subtitle}</p> : null}</div><Link href={href} className="mb-0.5 shrink-0 text-sm font-bold text-brand">Ver todos</Link></div>; }
const categories = [{ label: 'Comer', key: 'food', icon: Utensils }, { label: 'Café', key: 'cafe', icon: Coffee }, { label: 'Entrenar', key: 'fitness', icon: Dumbbell }, { label: 'Salir', key: 'nightlife', icon: Wine }, { label: 'Experiencias', key: 'experiences', icon: Sparkles }];
export default function Welcome({ featuredBenefits = [], featuredExperiences = [], membershipSummary, isPersonalizedHome = false, personalizationSubtitle }: { featuredBenefits?: BenefitSummary[]; featuredExperiences?: Experience[]; membershipSummary?: MembershipSummary | null; isPersonalizedHome?: boolean; personalizationSubtitle?: string | null }) {
 const { auth } = usePage().props; const name = auth.user?.name;
 return <><Head title="JAKAWI" /><main className="min-h-screen overflow-hidden bg-background pb-28 text-foreground"><section className="mx-auto w-full max-w-5xl pt-[max(2rem,env(safe-area-inset-top))] sm:px-6"><header className="px-4 sm:px-0"><div className="flex items-center justify-between gap-4"><p className="text-sm font-medium text-muted-foreground">{greeting(name)}</p><ThemeToggle /></div><h1 className="mt-3 max-w-xl text-[34px] leading-[1.02] font-extrabold tracking-tight sm:text-5xl">¿QUÉ HACEMOS HOY?</h1><p className="mt-4 max-w-lg text-base leading-6 text-muted-foreground">{auth.user ? 'Planes, lugares y beneficios pensados para que salgas más.' : 'Descubre nuevas razones para salir, probar y volver a tu ciudad.'}</p><Link href="/explorar" className="relative mt-6 flex min-h-13 items-center rounded-2xl border border-border bg-surface px-12 text-sm text-muted-foreground"><Search className="absolute left-4 size-5" />Buscar lugares, planes o experiencias</Link></header>
 <div className="mt-6 flex gap-3 overflow-x-auto px-4 pb-1 sm:px-0">{categories.map(({ label, key, icon: Icon }) => <Link key={key} href={`/explorar?category=${key}`} className="flex min-h-16 min-w-16 shrink-0 flex-col items-center justify-center gap-1 rounded-2xl border border-border bg-surface px-3 text-xs font-bold"><Icon className="size-5 text-brand" />{label}</Link>)}<Link href="/explorar" className="flex min-h-16 min-w-16 shrink-0 flex-col items-center justify-center gap-1 rounded-2xl border border-border bg-surface px-3 text-xs font-bold">Más</Link></div>
 {featuredBenefits[0] ? <section className="mx-4 mt-7 overflow-hidden rounded-[26px] bg-foreground text-background sm:mx-0"><Link href={`/beneficios/${featuredBenefits[0].slug}`} className="block">{featuredBenefits[0].image_url ? <img src={featuredBenefits[0].image_url} alt={featuredBenefits[0].title} className="aspect-[16/9] w-full object-cover" /> : null}<div className="p-5"><p className="text-xs font-bold tracking-wide text-background/70 uppercase">Recomendado por JAKAWI · {featuredBenefits[0].partner?.name}</p><h2 className="mt-2 text-2xl font-extrabold">{featuredBenefits[0].title}</h2><span className="mt-4 inline-flex rounded-xl bg-brand px-4 py-3 text-sm font-bold text-brand-foreground">Ver beneficio</span></div></Link></section> : featuredExperiences[0] ? <section className="mx-4 mt-7 overflow-hidden rounded-[26px] bg-foreground text-background sm:mx-0"><Link href={`/experiencias/${featuredExperiences[0].slug}`} className="block">{featuredExperiences[0].image_url ? <img src={featuredExperiences[0].image_url} alt={featuredExperiences[0].title} className="aspect-[16/9] w-full object-cover" /> : null}<div className="p-5"><p className="text-xs font-bold tracking-wide text-background/70 uppercase">Experiencia JAKAWI</p><h2 className="mt-2 text-2xl font-extrabold">{featuredExperiences[0].title}</h2><span className="mt-4 inline-flex rounded-xl bg-brand px-4 py-3 text-sm font-bold text-brand-foreground">Ver experiencia</span></div></Link></section> : null}
 {membershipSummary ? <div className={`mx-4 mt-8 rounded-[20px] p-4 sm:mx-0 ${membershipSummary.has_paid_for_itself ? 'bg-success text-success-foreground' : 'bg-surface-muted text-foreground'}`}><p className="text-sm font-bold">{membershipSummary.has_paid_for_itself ? 'Tu JAKAWI ya se pagó solo' : `Te faltan Bs ${membershipSummary.remaining_to_payback} para que tu JAKAWI se pague solo`}</p><p className="mt-1 text-sm opacity-75">Has ahorrado Bs {membershipSummary.confirmed_savings}</p></div> : null}
 {featuredBenefits.length ? <section className="mt-10"><SectionHeader title={isPersonalizedHome ? 'Beneficios para ti' : 'Beneficios destacados'} subtitle={personalizationSubtitle ?? 'Oportunidades para disfrutar más tu ciudad.'} href="/beneficios" /><div className="mt-4 flex gap-4 overflow-x-auto px-4 pb-2 [scrollbar-width:none] sm:grid sm:grid-cols-3 sm:px-0">{featuredBenefits.map(benefit => <BenefitCard key={benefit.id} benefit={benefit} />)}</div></section> : null}
 {featuredExperiences.length ? <section className="mt-10"><SectionHeader title={isPersonalizedHome ? 'Experiencias para ti' : 'Para vivir esta semana'} subtitle={isPersonalizedHome ? personalizationSubtitle : 'Momentos que no quieres dejar pasar.'} href="/experiencias" /><div className="mt-4 flex gap-4 overflow-x-auto px-4 pb-2 [scrollbar-width:none] sm:grid sm:grid-cols-3 sm:px-0">{featuredExperiences.map(experience => <ExperienceCard key={experience.id} experience={experience} />)}</div></section> : null}
 {!featuredBenefits.length && !featuredExperiences.length ? <section className="mx-4 mt-12 rounded-[22px] border border-border bg-surface p-7 text-center sm:mx-0"><Sparkles className="mx-auto size-7 text-brand" /><h2 className="mt-4 text-xl font-bold">Tu próxima salida empieza aquí</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Nuevos lugares están por llegar a JAKAWI.</p></section> : null}</section></main></>;
}
