import { Head, Link, router, usePage } from '@inertiajs/react';
import { useState } from 'react';
import JourneyLayout from '@/layouts/journey-layout';
type Challenge = { id: number; slug: string; title: string; description: string | null; status: string; ends_at: string | null; allowed_platforms: string[]; required_hashtags: string[]; required_mentions: string[]; qualification_mode: string; evaluation_mode: string; metric: 'views' | 'likes' | 'comments' | null; target: number | null; reward_type: string; reward_jp_amount: number | null; manual_prize_description: string | null };
type Participation = { id: number; social_url: string; platform: string | null; views: number | null; likes: number | null; comments: number | null; inspection_status: string; data_quality: string; validation_status: string; qualification_status: string; moderation_status: string | null; checked_at: string | null; sharecontest_payload?: { validation?: { checks?: Array<{ key?: string; status?: string; message?: string }> } }; refresh_pending: boolean };
type Grant = { id: number; status: string; reward_type: string; jp_amount: number | null; jp_reversed: boolean; benefit?: { title: string; slug: string }; locations?: Array<{ id: number; name: string }> };
export default function Show({ challenge, participation, grant, canParticipate, canSubmit, verificationUrl }: { challenge: Challenge; participation: Participation | null; grant: Grant | null; canParticipate: boolean; canSubmit: boolean; verificationUrl: string }) {
    const { auth, errors } = usePage().props as { auth: { user?: unknown }; errors: Record<string,string> };
    const [url,setUrl]=useState(''); const [location,setLocation]=useState<number | ''>('');
    const metricValue = participation && challenge.metric ? participation[challenge.metric] : null;
    return <JourneyLayout><Head title={challenge.title}/><main className="mx-auto max-w-3xl px-4 py-10"><Link href="/retos" className="underline">← Todos los retos</Link><h1 className="mt-6 text-4xl font-bold">{challenge.title}</h1><p className="mt-4 whitespace-pre-line">{challenge.description}</p><div className="mt-6 rounded-xl border p-5"><h2 className="font-semibold">Cómo participar</h2><p className="mt-2">Plataformas: {challenge.allowed_platforms.join(', ') || 'Las permitidas por el reto'}</p>{challenge.required_hashtags.length>0 && <p>Hashtags: {challenge.required_hashtags.join(' ')}</p>}{challenge.required_mentions.length>0 && <p>Menciones: {challenge.required_mentions.join(' ')}</p>}{challenge.ends_at && <p>Termina: {new Date(challenge.ends_at).toLocaleString('es-BO')}</p>}{challenge.qualification_mode==='METRIC_THRESHOLD' && <p>Objetivo: {challenge.target} {challenge.metric}</p>}{challenge.qualification_mode==='RANKED' && <p>Los ganadores se confirman después del cierre.</p>}{challenge.reward_type==='JP' && <p className="mt-3 font-semibold">Premio: {challenge.reward_jp_amount} JP</p>}</div>
        {!participation && canParticipate && <section id="participar" className="mt-8"><h2 className="text-2xl font-semibold">PARTICIPAR</h2>{!auth.user ? <button className="mt-4 rounded bg-primary px-5 py-3 text-primary-foreground" onClick={()=>router.post(`/retos/${challenge.slug}/participar`)}>Crear cuenta o ingresar</button> : !canSubmit ? <Link className="mt-4 inline-block underline" href={verificationUrl}>Verifica tu correo para participar</Link> : <form onSubmit={e=>{e.preventDefault();router.post(`/retos/${challenge.slug}/publicaciones`,{url});}} className="mt-4 flex flex-col gap-3"><label htmlFor="social-url">URL de tu publicación</label><input id="social-url" type="url" value={url} onChange={e=>setUrl(e.target.value)} required className="rounded border p-3" placeholder="https://..."/><button className="rounded bg-primary px-5 py-3 text-primary-foreground">Enviar publicación</button>{errors.url && <p role="alert" className="text-red-600">{errors.url}</p>}</form>}</section>}
        {participation && <section className="mt-8 rounded-xl border p-5"><h2 className="text-2xl font-semibold">Tu participación</h2><a href={participation.social_url} target="_blank" rel="noreferrer" className="mt-2 block break-all underline">Ver publicación</a>{participation.refresh_pending || participation.inspection_status==='pending' ? <p className="mt-3">Estamos verificando tu publicación.</p> : participation.validation_status==='invalid' ? <><p className="mt-3">La publicación no cumple las reglas del reto.</p>{participation.sharecontest_payload?.validation?.checks?.filter(x=>x.status==='invalid').map((x,i)=><p key={i}>{x.message || x.key}</p>)}</> : participation.qualification_status==='review_required' ? <p className="mt-3">Necesitamos verificar algunos datos.</p> : participation.qualification_status==='qualified' ? <p className="mt-3">Tu publicación calificó.</p> : participation.qualification_status==='not_qualified' ? <p className="mt-3">Tu publicación no calificó.</p> : <p className="mt-3">Tu participación sigue en evaluación.</p>}
            {challenge.qualification_mode==='METRIC_THRESHOLD' && participation.validation_status==='valid' && metricValue!==null && <p className="mt-3 font-semibold">Progreso: {metricValue} / {challenge.target} {challenge.metric}</p>}{participation.checked_at && <p className="mt-2 text-sm">Última revisión: {new Date(participation.checked_at).toLocaleString('es-BO')}</p>}{!participation.refresh_pending && challenge.status==='open' && <button className="mt-4 rounded border px-4 py-2" onClick={()=>router.post(`/retos/${challenge.slug}/actualizar`)}>ACTUALIZAR MI PUBLICACIÓN</button>}{errors.refresh && <p role="alert">{errors.refresh}</p>}</section>}
        {grant && <section className="mt-6 rounded-xl border p-5"><h2 className="text-xl font-semibold">Tu premio</h2><p>{grant.status==='fulfilled' ? 'Entregado' : grant.status==='granted' ? 'Concedido' : 'Cancelado'}</p>{grant.reward_type==='JP' ? <p>{grant.status==='granted' ? `Obtuviste ${grant.jp_amount} JP` : grant.jp_reversed ? `${grant.jp_amount} JP revertidos` : `${grant.jp_amount} JP cancelados`}</p> : grant.reward_type==='MANUAL_PRIZE' ? <p>{challenge.manual_prize_description}</p> : grant.benefit && <><p>{grant.benefit.title}</p>{grant.status==='granted' && <form onSubmit={e=>{e.preventDefault();router.post(`/beneficios/${grant.benefit!.slug}/canjear`,{location_id:location,social_challenge_reward_grant_id:grant.id});}} className="mt-3 flex flex-col gap-2"><select value={location} onChange={e=>setLocation(Number(e.target.value))} required className="rounded border p-2"><option value="">Elige una sucursal</option>{grant.locations?.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><button className="rounded bg-primary p-2 text-primary-foreground">Usar beneficio</button></form>}</>}</section>}</main></JourneyLayout>;
}
