import { Head, Link, router, usePage } from '@inertiajs/react';
import { useEffect, useRef, useState } from 'react';
import JourneyLayout from '@/layouts/journey-layout';
import { pollDelay, shouldPollEntry } from './entry-polling';

type C = {id:number;slug:string;title:string;description:string|null;instructions:string|null;status:string;evidence_type:string;starts_at:string|null;ends_at:string|null;allowed_platforms:string[];required_hashtags:string[];required_mentions:string[];qualification_type:string;qualification_metric:'likes'|'views'|'comments'|null;qualification_target:number|null;selection_type:string;selection_metric:'likes'|'views'|'comments'|null;winner_limit:number|null;review_mode:string;participation_eligibility:string;reward_eligibility:string;max_entries_per_user:number|null;reward_type:string;reward_jp_amount:number|null;manual_prize_description:string|null};
type Requirement = {key:string;label:string;status:'PASS'|'FAIL'|'UNKNOWN';value?:string};
type E = {entry_id:number;social_url:string;platform:string|null;likes:number|null;views:number|null;comments:number|null;inspection_status:string;validation_status:string;data_quality:string;checked_at:string|null;refresh_pending:boolean;requirements:Requirement[]};
type P = {id:number;qualification_status:string;qualified_entry_id:number|null;selection_status:string;selected_entry_id:number|null};
type G = {id:number;status:string;reward_type:string;jp_amount:number|null;jp_reversed:boolean;benefit?:{title:string;slug:string};locations?:Array<{id:number;name:string}>};
type R = {metric:string;updated_at:string|null;threshold:number|null;official:boolean;rows:Array<{name:string;score:number;position:number;is_you:boolean;provisional_top:boolean;confirmed:boolean}>};
const metric=(m:string|null)=>({likes:'likes',views:'vistas',comments:'comentarios'} as Record<string,string>)[m??'']??'interacciones';
const date=(s:string|null)=>s?new Intl.DateTimeFormat('es-BO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(s)):'Por anunciar';
const freshness=(s:string|null)=>{if(!s)return 'Aún sin datos verificados';const mins=Math.max(0,Math.floor((Date.now()-new Date(s).getTime())/60000));return mins<60?`Actualizado hace ${mins} min`:`Actualizado hace ${Math.floor(mins/60)} h`;};
function status(p:P,es:E[],g:G|null) { if(g?.status==='granted'||g?.status==='fulfilled') return '¡Ganaste!'; if(p.selection_status==='candidate') return 'Estás entre los candidatos'; if(p.qualification_status==='qualified') return '¡Cumpliste el reto!'; if(es.some(e=>e.validation_status==='valid')) return 'Tu publicación cumple las reglas'; if(es.some(e=>e.inspection_status==='failed')) return 'No pudimos verificar tu publicación todavía'; if(es.some(e=>e.refresh_pending)) return 'Estamos verificando tu publicación'; if(es.some(e=>e.validation_status==='invalid')) return 'Tu publicación todavía no cumple'; if(p.selection_status==='review_required'||p.qualification_status==='review_required') return 'JAKAWI está revisando el resultado'; return 'Estamos verificando tu publicación'; }
function EntryCard({entry:e,index,c,qualified,best,canAdd,slow,highlight}:{entry:E;index:number;c:C;qualified:boolean;best:boolean;canAdd:boolean;slow:boolean;highlight:boolean}) {
 const inspecting=e.refresh_pending&&e.inspection_status!=='failed';
 const failed=e.inspection_status==='failed';
 const invalid=!e.refresh_pending&&e.validation_status==='invalid';
 const valid=!e.refresh_pending&&e.validation_status==='valid';
 const currentMetric=c.qualification_metric?e[c.qualification_metric]:null;
 const below=valid&&c.qualification_type==='METRIC_THRESHOLD'&&c.qualification_target!==null&&currentMetric!==null&&currentMetric<c.qualification_target;
 const title=failed?'No pudimos verificar tu publicación todavía':inspecting?'Estamos verificando tu publicación':invalid?'Tu publicación todavía no cumple':below?'Tu publicación cumple las reglas':valid?'¡Publicación verificada!':'Estamos revisando tu publicación';
 return <article className={`rounded-2xl border p-4 ${highlight?'border-brand':''}`} aria-live="polite"><a href={e.social_url} target="_blank" rel="noreferrer" className="font-bold underline">Publicación {index+1}</a>{best&&<span className="ml-2 rounded-full bg-brand-subtle px-2 py-1 text-xs font-bold">Tu mejor publicación</span>}
  <h3 className="mt-2 text-lg font-extrabold">{title}</h3>
  {inspecting&&<p className="mt-1 text-sm">{slow?'Esto está tardando un poco más de lo normal. Seguimos verificando tu publicación.':'Normalmente tarda solo unos segundos.'}</p>}
  {failed&&<p className="mt-1 text-sm">No la marcamos como inválida. Intentaremos actualizarla nuevamente.{e.refresh_pending?(slow?' Esto está tardando un poco más de lo normal. Seguimos verificando tu publicación.':' Seguimos verificando tu publicación.'):''}</p>}
  {!failed&&!inspecting&&e.requirements.length>0&&<ul className="mt-3 space-y-1 text-sm">{e.requirements.map(rule=><li key={rule.key}><span aria-hidden="true">{rule.status==='PASS'?'✓':rule.status==='FAIL'?'✕':'?'}</span> {rule.status==='FAIL'&&rule.key.startsWith('hashtag:')?'Falta ':''}{rule.label}{rule.status==='UNKNOWN'?' · por confirmar':''}</li>)}</ul>}
  {valid&&c.qualification_type==='VALID_EVIDENCE'&&qualified&&<p className="mt-2 font-bold">¡Cumpliste el reto!</p>}
  {below&&c.qualification_metric&&c.qualification_target!==null&&currentMetric!==null&&<p className="mt-2 font-bold">{currentMetric} / {c.qualification_target} {metric(c.qualification_metric)} · Te faltan {c.qualification_target-currentMetric} {metric(c.qualification_metric)}.</p>}
  <p className="mt-2 text-sm">{e.platform||'Plataforma por verificar'} · {e.likes??'—'} likes · {e.views??'—'} vistas · {e.comments??'—'} comentarios</p>
  <p className="mt-1 text-xs text-muted-foreground">Última actualización: {e.checked_at?date(e.checked_at):'Pendiente'}</p>
  {invalid&&canAdd&&<a href="#participar" className="mt-3 inline-flex min-h-11 items-center rounded-xl bg-brand px-3 text-sm font-extrabold text-brand-foreground">ENVIAR OTRA PUBLICACIÓN</a>}
  {!e.refresh_pending&&c.status==='open'&&<button className="mt-3 min-h-11 rounded-xl border px-3 text-sm font-bold" onClick={()=>router.post(`/retos/${c.slug}/actualizar`,{entry_id:e.entry_id})}>VOLVER A VERIFICAR</button>}
 </article>;
}
export default function Show({challenge:c,heroUrl,rewardLabel,participation:initialParticipation,entries:initialEntries,grant:initialGrant,submittedEntryId,canParticipate,canSubmit,isMember=false,slots,ranking,preview=false,verificationUrl}:{challenge:C;heroUrl?:string|null;rewardLabel?:string|null;participation:P|null;entries:E[];grant:G|null;submittedEntryId?:number|null;canParticipate:boolean;canSubmit:boolean;isMember?:boolean;slots?:{awarded:number;reserved:number;limit:number}|null;ranking?:R|null;preview?:boolean;verificationUrl:string}) {
 const {auth,errors}=usePage().props as {auth:{user?:{id:number}|null};errors:Record<string,string>};
 const [url,setUrl]=useState('');const [location,setLocation]=useState<number|''>('');
 const [es,setEntries]=useState(initialEntries);const [p,setParticipation]=useState(initialParticipation);const [g,setGrant]=useState(initialGrant);
 const [submitting,setSubmitting]=useState(false);const submittingRef=useRef(false);const [slow,setSlow]=useState(false);
 useEffect(()=>{setEntries(initialEntries);setParticipation(initialParticipation);setGrant(initialGrant);},[initialEntries,initialParticipation,initialGrant]);
 const pendingIds=es.filter(shouldPollEntry).map(e=>e.entry_id).join(',');
 useEffect(()=>{
  if(!pendingIds)return;
  const ids=pendingIds.split(',').map(Number);const controller=new AbortController();const startedAt=Date.now();let timer:ReturnType<typeof setTimeout>;
  setSlow(false);
  const slowTimer=setTimeout(()=>setSlow(true),15_000);
  const poll=async()=>{
   const responses=await Promise.all(ids.map(async id=>{
    try {const response=await fetch(`/retos/${encodeURIComponent(c.slug)}/publicaciones/${id}/estado`,{credentials:'same-origin',headers:{Accept:'application/json'},signal:controller.signal});return response.ok?await response.json() as E&{participation:P;grant:G|null}:null;}
    catch{return null;}
   }));
   if(controller.signal.aborted)return;
   for(const state of responses){if(!state)continue;setEntries(current=>current.map(entry=>entry.entry_id===state.entry_id?{...entry,...state}:entry));setParticipation(state.participation);setGrant(state.grant);}
   const elapsed=Date.now()-startedAt;setSlow(elapsed>=15_000);
   if(responses.some(state=>state===null||shouldPollEntry(state)))timer=setTimeout(poll,pollDelay(elapsed));
  };
  timer=setTimeout(poll,1_000);
  return()=>{controller.abort();clearTimeout(timer);clearTimeout(slowTimer);};
 },[pendingIds,c.slug]);
 const canAdd=c.evidence_type==='SOCIAL_POST'&&canParticipate&&canSubmit&&(c.max_entries_per_user===null||es.length<c.max_entries_per_user);
 const best=c.selection_type==='TOP_N'&&c.selection_metric?es.filter(e=>e.validation_status==='valid').sort((a,b)=>(b[c.selection_metric!]??0)-(a[c.selection_metric!]??0))[0]:es.find(e=>e.entry_id===p?.qualified_entry_id);
 const progress=c.qualification_type==='METRIC_THRESHOLD'&&c.qualification_metric?Math.max(0,...es.filter(e=>e.validation_status==='valid').map(e=>e[c.qualification_metric!]??0)):null;
 const reward=c.reward_type==='JP'?`${c.reward_jp_amount} JP`:c.reward_type==='MANUAL_PRIZE'?c.manual_prize_description:rewardLabel??g?.benefit?.title??'Un beneficio JAKAWI';
 const qualification=c.qualification_type==='METRIC_THRESHOLD'?`Consigue al menos ${c.qualification_target} ${metric(c.qualification_metric)}`:c.qualification_type==='MANUAL'?'JAKAWI confirmará que cumpliste el reto':'Cumple las reglas del reto';
 const selection=c.selection_type==='FIRST_N'?`Los primeros ${c.winner_limit} participantes verificados reciben el premio`:c.selection_type==='TOP_N'?`Las ${c.winner_limit} participaciones con más ${metric(c.selection_metric)} al cierre`:c.selection_type==='MANUAL'?'JAKAWI seleccionará a los ganadores según las reglas del reto':'Todos los que cumplan reciben el premio';
 const rules:[string,string][]=[['Qué tienes que hacer',c.instructions|| (c.evidence_type==='SOCIAL_POST'?'Publica contenido y envía el enlace.':'Sigue las instrucciones del reto.')],['Cómo participar',c.evidence_type==='SOCIAL_POST'?'Envía una publicación para empezar. Puedes agregar más hasta el límite indicado.':'Pulsa Participar. JAKAWI revisará tu cumplimiento.'],['Qué necesitas cumplir',qualification],['Cómo se eligen ganadores',selection],['Premios disponibles',String(c.winner_limit??'Uno para cada participante que cumpla')],['Qué ganas',reward??'Premio por anunciar'],['Quién puede participar',c.participation_eligibility==='ALL_USERS'?'Todas las personas con cuenta JAKAWI':'Personas con membresía JAKAWI activa'],['Membresía para recibir el premio',c.reward_eligibility==='ACTIVE_MEMBERS'?'Puedes participar gratis. Necesitas una membresía JAKAWI activa para recibir el premio.':'No se exige membresía activa para recibir el premio.'],['Inicio',date(c.starts_at)],['Cierre',date(c.ends_at)],['Revisión JAKAWI',c.review_mode==='REQUIRED'?'Los resultados serán revisados por JAKAWI antes de confirmar ganadores.':'JAKAWI verifica el cumplimiento de las reglas.']];
 if(c.evidence_type==='SOCIAL_POST'){rules.splice(8,0,['Publicaciones por persona',String(c.max_entries_per_user??'Sin límite configurado')]);if(c.allowed_platforms?.length)rules.splice(9,0,['Plataformas',c.allowed_platforms.join(', ')]);if(c.required_hashtags?.length)rules.splice(9,0,['Etiquetas',c.required_hashtags.join(' ')]);if(c.required_mentions?.length)rules.splice(9,0,['Menciones',c.required_mentions.join(' ')])}
 return <JourneyLayout><Head title={c.title}/><main className="mx-auto max-w-3xl px-4 pb-28 pt-7 text-foreground"><Link href="/retos" className="text-sm font-bold text-brand">← RETOS</Link>{preview&&<p className="mt-5 rounded-xl bg-brand-subtle p-3 text-sm font-bold">Vista previa para Partner</p>}
 <header className="mt-7">{heroUrl&&<img src={heroUrl} alt="" className="mb-6 aspect-[16/9] w-full rounded-3xl object-cover"/>}<p className="text-xs font-extrabold tracking-[0.15em] text-brand">RETO</p><h1 className="mt-2 text-4xl font-extrabold leading-tight">{c.title}</h1><p className="mt-4 whitespace-pre-line text-lg leading-7">{c.description}</p></header>
 <section className="mt-7 rounded-3xl bg-surface-elevated p-5 shadow-editorial"><h2 className="text-xl font-extrabold">Así funciona</h2><dl className="mt-4 space-y-4 text-sm leading-6">{rules.map(([title,value])=><div key={title}><dt className="font-extrabold">{title}</dt><dd>{value}</dd></div>)}</dl></section>
 {slots&&<section className="mt-6 rounded-3xl bg-brand-subtle p-5"><h2 className="text-xs font-extrabold tracking-widest">PREMIOS</h2><p className="mt-2 text-3xl font-extrabold">{slots.awarded} / {slots.limit} otorgados</p><p>Quedan {Math.max(0,slots.limit-slots.reserved)} premios disponibles.</p></section>}
 {p&&<section className="mt-7 rounded-3xl border border-brand p-5"><h2 className="text-xs font-extrabold tracking-widest text-brand">TU RETO</h2><p className="mt-2 text-2xl font-extrabold">{status(p,es,g)}</p>{progress!==null&&c.qualification_target&&<div className="mt-4"><p className="text-xl font-bold">{progress} / {c.qualification_target} {metric(c.qualification_metric)}</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-surface-muted"><div className="h-full bg-brand" style={{width:`${Math.min(100,progress/c.qualification_target*100)}%`}}/></div><p className="mt-2 text-sm">{progress>=c.qualification_target?'Cumpliste la meta.':`Te faltan ${c.qualification_target-progress} ${metric(c.qualification_metric)}.`}</p></div>}{p.qualification_status==='qualified'&&c.reward_eligibility==='ACTIVE_MEMBERS'&&!isMember&&!g&&<div className="mt-5"><p className="font-bold">Para recibir este premio necesitas una membresía JAKAWI activa.</p>{slots&&<p className="mt-1 text-sm">Activa tu membresía mientras queden premios disponibles.</p>}<Link href={`/membresia?journey=SOCIAL_CHALLENGE&action=PARTICIPATE&resource_id=${c.id}`} className="mt-3 inline-flex min-h-11 items-center rounded-xl bg-brand px-4 font-extrabold text-brand-foreground">ACTIVAR MEMBRESÍA</Link></div>}</section>}
 {canParticipate&&!auth.user&&<button className="mt-7 min-h-12 rounded-xl bg-brand px-5 font-extrabold text-brand-foreground" onClick={()=>router.post(`/retos/${c.slug}/participar`)}>CREAR CUENTA O INGRESAR</button>}
 {canParticipate&&Boolean(auth.user)&&!canSubmit&&<p className="mt-7"><Link href={verificationUrl} className="underline">Verifica tu correo</Link> o revisa los requisitos de membresía para participar.</p>}
 {canParticipate&&canSubmit&&c.evidence_type==='MANUAL'&&!p&&<button className="mt-7 min-h-12 rounded-xl bg-brand px-5 font-extrabold text-brand-foreground" onClick={()=>router.post(`/retos/${c.slug}/participar`)}>PARTICIPAR</button>}
 {canAdd&&<form id="participar" className="mt-7 space-y-3" onSubmit={e=>{e.preventDefault();if(submittingRef.current)return;submittingRef.current=true;setSubmitting(true);router.post(`/retos/${c.slug}/publicaciones`,{url},{onSuccess:()=>setUrl(''),onFinish:()=>{submittingRef.current=false;setSubmitting(false);}});}}><h2 className="text-xl font-extrabold">{es.length?'AGREGAR OTRA PUBLICACIÓN':'PARTICIPAR'}</h2><label htmlFor="social-url" className="block text-sm font-bold">Enlace de tu publicación</label><input id="social-url" type="url" value={url} onChange={e=>setUrl(e.target.value)} required className="min-h-12 w-full rounded-xl border p-3" placeholder="https://..."/><button disabled={submitting} className="min-h-12 rounded-xl bg-brand px-5 font-extrabold text-brand-foreground disabled:opacity-60">{submitting?'ENVIANDO...':'ENVIAR PUBLICACIÓN'}</button>{errors.url&&<p role="alert" className="text-red-600">{errors.url}</p>}</form>}
 {es.length>0&&<section className="mt-8"><h2 className="text-xl font-extrabold">MIS PUBLICACIONES</h2><div className="mt-3 space-y-3">{es.map((e,i)=><EntryCard key={e.entry_id} entry={e} index={i} c={c} qualified={p?.qualification_status==='qualified'&&p.qualified_entry_id===e.entry_id} best={best?.entry_id===e.entry_id} canAdd={canAdd} slow={slow} highlight={submittedEntryId===e.entry_id}/>)}</div>{errors.refresh&&<p role="alert" className="mt-2 text-red-600">{errors.refresh}</p>}</section>}
 {ranking&&<section className="mt-8 rounded-3xl border p-5"><h2 className="text-xl font-extrabold">{ranking.official?'Ganadores confirmados':c.status==='closed'?'Resultado provisional':'Ranking provisional'}</h2><p className="mt-1 text-sm text-muted-foreground">{freshness(ranking.updated_at)}{ranking.threshold?` · Meta mínima: ${ranking.threshold} ${metric(ranking.metric)}`:''}</p>{c.status==='open'&&<p className="mt-2 text-sm">La posición puede cambiar hasta el cierre.</p>}<ol className="mt-4 divide-y">{ranking.rows.map(row=><li key={row.position} className={`flex justify-between gap-3 py-3 text-sm ${row.is_you?'font-extrabold text-brand':''}`}><span>{row.position}. {row.is_you?'Tú':row.name}{row.is_you&&row.provisional_top&&!ranking.official?' · Dentro del Top provisional':''}</span><span>{row.score.toLocaleString('es-BO')} {metric(ranking.metric)}</span></li>)}</ol></section>}
 {g&&<section className="mt-7 rounded-3xl bg-success-surface p-5"><h2 className="text-xl font-extrabold">TU PREMIO</h2><p className="mt-2">{g.status==='fulfilled'?'Entregado':g.status==='granted'?'¡Ganaste!':'Premio cancelado'}</p>{g.reward_type==='JP'?<p>{g.status==='granted'?`+${g.jp_amount} JP`:g.jp_reversed?`${g.jp_amount} JP revertidos`:`${g.jp_amount} JP cancelados`}</p>:g.reward_type==='MANUAL_PRIZE'?<p>{c.manual_prize_description}</p>:g.benefit&&<><p>{g.benefit.title}</p>{g.status==='granted'&&<form onSubmit={e=>{e.preventDefault();router.post(`/beneficios/${g.benefit!.slug}/canjear`,{location_id:location,social_challenge_reward_grant_id:g.id});}} className="mt-3 flex flex-col gap-2"><select value={location} onChange={e=>setLocation(Number(e.target.value))} required className="rounded border p-2"><option value="">Elige una sucursal</option>{g.locations?.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><button className="rounded bg-brand p-2 text-brand-foreground">Usar beneficio</button></form>}</>}</section>}
 </main></JourneyLayout>;
}
