import { Head, Link, router, usePage } from '@inertiajs/react';
import { useState } from 'react';
import JourneyLayout from '@/layouts/journey-layout';

type Challenge = { slug:string; title:string; description:string|null; status:string; evidence_type:'SOCIAL_POST'|'MANUAL'; starts_at:string|null; ends_at:string|null; allowed_platforms:string[]; required_hashtags:string[]; required_mentions:string[]; qualification_type:string; qualification_metric:'views'|'likes'|'comments'|null; qualification_target:number|null; selection_type:string; selection_metric:string|null; winner_limit:number|null; review_mode:string; participation_eligibility:string; reward_eligibility:string; max_entries_per_user:number|null; reward_type:string; reward_jp_amount:number|null; manual_prize_description:string|null };
type Entry = { id:number; social_url:string; views:number|null; likes:number|null; comments:number|null; inspection_status:string; validation_status:string; checked_at:string|null; refresh_pending:boolean; sharecontest_payload?:{validation?:{checks?:Array<{key?:string;status?:string;message?:string}>}} };
type Participation = { id:number; qualification_status:string; qualified_entry_id:number|null; selection_status:string; selected_entry_id:number|null };
type Grant = { id:number; status:string; reward_type:string; jp_amount:number|null; jp_reversed:boolean; benefit?:{title:string;slug:string}; locations?:Array<{id:number;name:string}> };

export default function Show({challenge,participation,entries,grant,canParticipate,canSubmit,verificationUrl}:{challenge:Challenge;participation:Participation|null;entries:Entry[];grant:Grant|null;canParticipate:boolean;canSubmit:boolean;verificationUrl:string}) {
    const {auth,errors}=usePage().props as {auth:{user?:{id:number}|null};errors:Record<string,string>};
    const [url,setUrl]=useState(''); const [location,setLocation]=useState<number|''>('');
    const canAdd=challenge.evidence_type==='SOCIAL_POST' && canParticipate && canSubmit && (challenge.max_entries_per_user===null || entries.length<challenge.max_entries_per_user);
    return <JourneyLayout><Head title={challenge.title}/><main className="mx-auto max-w-3xl px-4 py-10"><Link href="/retos" className="underline">← Todos los retos</Link><h1 className="mt-6 text-4xl font-bold">{challenge.title}</h1><p className="mt-4 whitespace-pre-line">{challenge.description}</p>
        <section className="mt-6 rounded-xl border p-5"><h2 className="font-semibold">Reglas del reto</h2><p className="mt-2">Qué hacer: {challenge.evidence_type==='SOCIAL_POST' ? 'Enviar una o varias publicaciones' : 'Inscribirte para revisión manual'}</p><p>Evidencia: {challenge.evidence_type==='SOCIAL_POST'?'Publicación social':'Manual'}</p><p>Participan: {challenge.participation_eligibility==='ALL_USERS'?'Todos los usuarios':'Miembros activos'}</p><p>Calificación: {challenge.qualification_type==='METRIC_THRESHOLD' ? `${challenge.qualification_metric} ≥ ${challenge.qualification_target}` : challenge.qualification_type==='VALID_EVIDENCE'?'Evidencia válida':'Revisión manual'}</p><p>Selección: {challenge.selection_type}{challenge.winner_limit ? ` · máximo ${challenge.winner_limit} ganadores` : ''}{challenge.selection_metric ? ` · ${challenge.selection_metric}` : ''}</p><p>Premio: {challenge.reward_type==='JP'?`${challenge.reward_jp_amount} JP`:challenge.reward_type==='MANUAL_PRIZE'?challenge.manual_prize_description:'Beneficio'}</p><p>Reciben premio: {challenge.reward_eligibility==='ALL_USERS'?'Todos los usuarios elegibles':'Miembros activos'}</p><p>Revisión: {challenge.review_mode==='REQUIRED'?'JAKAWI confirma los candidatos':'Automática'}</p>{challenge.starts_at&&<p>Inicia: {new Date(challenge.starts_at).toLocaleString('es-BO')}</p>}{challenge.ends_at&&<p>Termina: {new Date(challenge.ends_at).toLocaleString('es-BO')}</p>}{challenge.evidence_type==='SOCIAL_POST'&&<><p>Publicaciones por usuario: {challenge.max_entries_per_user??'sin límite configurado'}</p><p>Plataformas: {challenge.allowed_platforms.join(', ')||'Las permitidas por el reto'}</p>{challenge.required_hashtags.length>0&&<p>Hashtags: {challenge.required_hashtags.join(' ')}</p>}{challenge.required_mentions.length>0&&<p>Menciones: {challenge.required_mentions.join(' ')}</p>}</>}</section>
        {canParticipate && !auth.user && <button className="mt-8 rounded bg-primary px-5 py-3 text-primary-foreground" onClick={()=>router.post(`/retos/${challenge.slug}/participar`)}>Crear cuenta o ingresar</button>}
        {canParticipate && Boolean(auth.user) && !canSubmit && <p className="mt-8"><Link href={verificationUrl} className="underline">Verifica tu correo</Link> o revisa los requisitos de membresía para participar.</p>}
        {canParticipate && canSubmit && challenge.evidence_type==='MANUAL' && !participation && <button className="mt-8 rounded bg-primary px-5 py-3 text-primary-foreground" onClick={()=>router.post(`/retos/${challenge.slug}/participar`)}>Participar</button>}
        {canAdd && <form id="participar" className="mt-8 flex flex-col gap-3" onSubmit={e=>{e.preventDefault();router.post(`/retos/${challenge.slug}/publicaciones`,{url},{onSuccess:()=>setUrl('')});}}><h2 className="text-2xl font-semibold">{entries.length?'Agregar otra publicación':'Participar'}</h2><label htmlFor="social-url">URL de tu publicación</label><input id="social-url" type="url" value={url} onChange={e=>setUrl(e.target.value)} required className="rounded border p-3" placeholder="https://..."/><button className="rounded bg-primary px-5 py-3 text-primary-foreground">Enviar publicación</button>{errors.url&&<p role="alert" className="text-red-600">{errors.url}</p>}</form>}
        {participation&&<section className="mt-8 rounded-xl border p-5"><h2 className="text-2xl font-semibold">Tu participación</h2><p>Calificación: {participation.qualification_status}</p><p>Selección: {participation.selection_status}</p>{participation.selection_status==='candidate'&&<p>Pendiente de confirmación JAKAWI.</p>}{challenge.reward_eligibility==='ACTIVE_MEMBERS'&&!grant&&<p>La membresía activa es necesaria para recibir el premio.</p>}{entries.map(e=><div key={e.id} className="mt-5 border-t pt-4"><a href={e.social_url} target="_blank" rel="noreferrer" className="break-all underline">Publicación #{e.id}</a>{participation.qualified_entry_id===e.id&&<span className="ml-2"> · Calificó</span>}{participation.selected_entry_id===e.id&&<span className="ml-2"> · Mejor entrada</span>}<p>Validación: {e.validation_status} · {e.inspection_status}</p><p>Vistas {e.views??'—'} · Likes {e.likes??'—'} · Comentarios {e.comments??'—'}</p>{e.checked_at&&<p>Revisada: {new Date(e.checked_at).toLocaleString('es-BO')}</p>}{e.sharecontest_payload?.validation?.checks?.filter(x=>x.status==='invalid').map((x,i)=><p key={i}>{x.message||x.key}</p>)}{!e.refresh_pending&&challenge.status==='open'&&<button className="mt-2 rounded border px-3 py-1" onClick={()=>router.post(`/retos/${challenge.slug}/actualizar`,{entry_id:e.id})}>Actualizar esta publicación</button>}{e.refresh_pending&&<p>Verificación pendiente.</p>}</div>)}{errors.refresh&&<p role="alert">{errors.refresh}</p>}</section>}
        {grant&&<section className="mt-6 rounded-xl border p-5"><h2 className="text-xl font-semibold">Tu premio</h2><p>{grant.status==='fulfilled'?'Entregado':grant.status==='granted'?'Concedido':'Cancelado'}</p>{grant.reward_type==='JP'?<p>{grant.status==='granted'?`Obtuviste ${grant.jp_amount} JP`:grant.jp_reversed?`${grant.jp_amount} JP revertidos`:`${grant.jp_amount} JP cancelados`}</p>:grant.reward_type==='MANUAL_PRIZE'?<p>{challenge.manual_prize_description}</p>:grant.benefit&&<><p>{grant.benefit.title}</p>{grant.status==='granted'&&<form onSubmit={e=>{e.preventDefault();router.post(`/beneficios/${grant.benefit!.slug}/canjear`,{location_id:location,social_challenge_reward_grant_id:grant.id});}} className="mt-3 flex flex-col gap-2"><select value={location} onChange={e=>setLocation(Number(e.target.value))} required className="rounded border p-2"><option value="">Elige una sucursal</option>{grant.locations?.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><button className="rounded bg-primary p-2 text-primary-foreground">Usar beneficio</button></form>}</>}</section>}
    </main></JourneyLayout>;
}
