<?php
namespace App\Services;
use App\Models\AuditLog; use App\Models\JpHold; use App\Models\Unlock; use App\Models\UnlockParticipation; use App\Models\UnlockStatusHistory; use App\Models\User; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class UnlockParticipationService {
 public function interest(Unlock $unlock,User $user): UnlockParticipation { return DB::transaction(function()use($unlock,$user){$u=Unlock::lockForUpdate()->findOrFail($unlock->id);$p=UnlockParticipation::firstOrNew(['unlock_id'=>$u->id,'user_id'=>$user->id]);if($p->status!==UnlockParticipation::COMMITTED){$p->status=UnlockParticipation::INTERESTED;$p->interested_at??=now();$p->save();}return $p;}); }
 public function commit(Unlock $unlock,User $user): UnlockParticipation { return DB::transaction(function()use($unlock,$user){$user=User::lockForUpdate()->findOrFail($user->id);$u=Unlock::lockForUpdate()->findOrFail($unlock->id);if(!in_array($u->status,[Unlock::ACTIVE,Unlock::GOAL_REACHED],true)||($u->starts_at&&$u->starts_at->isFuture())||($u->commitment_deadline&&$u->commitment_deadline->isPast()))throw ValidationException::withMessages(['unlock'=>'Este desbloqueo no acepta compromisos.']);if($u->jp_deposit>0&&!config('unlocks.jp_commitments_enabled'))throw ValidationException::withMessages(['unlock'=>'Los compromisos con JP aún no están activos.']);$member=$user->hasActiveMembership();if((!$member&&!$u->free_user_eligible)||($member&&!$u->member_eligible))throw ValidationException::withMessages(['unlock'=>'No eres elegible para este desbloqueo.']);$p=UnlockParticipation::where('unlock_id',$u->id)->where('user_id',$user->id)->lockForUpdate()->first();if($p?->status===UnlockParticipation::COMMITTED)return $p;$count=UnlockParticipation::where('unlock_id',$u->id)->where('status',UnlockParticipation::COMMITTED)->count();if($u->maximum_capacity!==null&&$count>=$u->maximum_capacity)throw ValidationException::withMessages(['unlock'=>'Este desbloqueo está completo.']);if($u->jp_deposit>0){$balance=app(JpBalanceService::class)->for($user);if($balance['spendable']<$u->jp_deposit)throw ValidationException::withMessages(['jp'=>'Necesitas '.($u->jp_deposit-$balance['spendable']).' JP más para utilizar como garantía.']);}$p??=new UnlockParticipation(['unlock_id'=>$u->id,'user_id'=>$user->id]);$p->status=UnlockParticipation::COMMITTED;$p->committed_at=now();$p->save();if($u->jp_deposit>0){$hold=JpHold::firstOrCreate(['unlock_participation_id'=>$p->id],['user_id'=>$user->id,'amount'=>$u->jp_deposit,'status'=>JpHold::HELD,'reason'=>'unlock_commitment','held_at'=>now()]);AuditLog::create(['actor_user_id'=>$user->id,'action'=>'unlock_jp_held','subject_type'=>JpHold::class,'subject_id'=>$hold->id,'metadata'=>['unlock_id'=>$u->id,'amount'=>$u->jp_deposit]]);}if($u->goal_reached_at===null&&$count+1>=$u->minimum_commitments){$u->status=Unlock::GOAL_REACHED;$u->goal_reached_at=now();$u->status_changed_at=now();$u->save();UnlockStatusHistory::create(['unlock_id'=>$u->id,'from_status'=>Unlock::ACTIVE,'to_status'=>Unlock::GOAL_REACHED,'reason'=>'Minimum commitments reached']);}return $p;}); }
 public function cancel(Unlock $unlock,User $user): UnlockParticipation{return DB::transaction(function()use($unlock,$user){$u=Unlock::lockForUpdate()->findOrFail($unlock->id);$p=UnlockParticipation::where('unlock_id',$u->id)->where('user_id',$user->id)->lockForUpdate()->firstOrFail();if($p->status!==UnlockParticipation::COMMITTED)throw ValidationException::withMessages(['unlock'=>'No tienes un compromiso activo.']);if($u->cancellation_deadline&&$u->cancellation_deadline->isPast())throw ValidationException::withMessages(['unlock'=>'El plazo de cancelación terminó.']);$p->update(['status'=>UnlockParticipation::CANCELLED_ON_TIME,'cancelled_at'=>now()]);$this->release($p,$user->id,'user_cancellation');return $p;});}
 public function releaseForUnlock(Unlock $unlock,string $reason):void{DB::transaction(function()use($unlock,$reason){foreach(JpHold::where('status',JpHold::HELD)->whereHas('participation',fn($q)=>$q->where('unlock_id',$unlock->id))->lockForUpdate()->get() as $hold){$hold->update(['status'=>JpHold::RELEASED,'released_at'=>now()]);AuditLog::create(['action'=>'unlock_jp_released','subject_type'=>JpHold::class,'subject_id'=>$hold->id,'metadata'=>['unlock_id'=>$unlock->id,'amount'=>$hold->amount,'reason'=>$reason]]);}});}
 private function release(UnlockParticipation $p,int $actor,string $reason):void{$hold=JpHold::where('unlock_participation_id',$p->id)->lockForUpdate()->first();if(!$hold||$hold->status!==JpHold::HELD)return;$hold->update(['status'=>JpHold::RELEASED,'released_at'=>now()]);AuditLog::create(['actor_user_id'=>$actor,'action'=>'unlock_jp_released','subject_type'=>JpHold::class,'subject_id'=>$hold->id,'metadata'=>['unlock_id'=>$p->unlock_id,'amount'=>$hold->amount,'reason'=>$reason]]);}
}
