import { Head, Link, router, usePage } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '../layout';

type Presentation={id:number;name:string;slug:string;status:'DRAFT'|'PUBLISHED'|'ARCHIVED';default_scope:'NONE'|'GUESTS'|'ALL';campaign_key:string|null;eyebrow:string|null;headline:string|null;subheadline:string|null;hero_path:string|null;hero_alt:string|null;reward_display_override:string|null;final_cta_headline:string|null};
const empty={name:'',slug:'',campaign_key:'',eyebrow:'',headline:'',subheadline:'',hero_path:'',hero_alt:'',reward_display_override:'',final_cta_headline:''};
export default function Index({subject,presentations,baseUrl,productUrl}:{baseUrl?:string;productUrl?:string;subject:{title:string;slug:string};presentations:Presentation[]}) {
    const base=baseUrl??`/admin/retos/${subject.slug}/landings`;
    const {errors}=usePage().props as {errors:Record<string,string>};
    const [editing,setEditing]=useState<Presentation|null>(null);
    const [open,setOpen]=useState(false);
    const [form,setForm]=useState<Record<string,string>>(empty);
    const field=(key:string,label:string,multiline=false)=><label className="flex flex-col gap-1 text-sm font-bold">{label}{multiline?<textarea className="min-h-24 rounded border border-border bg-surface p-3 font-normal" value={form[key]??''} onChange={event=>setForm(x=>({...x,[key]:event.target.value}))}/>:<input className="rounded border border-border bg-surface p-3 font-normal" value={form[key]??''} onChange={event=>setForm(x=>({...x,[key]:event.target.value}))}/>} {errors[key]&&<span className="text-danger">{errors[key]}</span>}</label>;
    const begin=(item:Presentation|null)=>{setEditing(item);setOpen(true);setForm(item?Object.fromEntries(Object.keys(empty).map(key=>[key,String(item[key as keyof Presentation]??'')])):empty);};
    const defaultItem=presentations.find(item=>item.status==='PUBLISHED'&&item.default_scope!=='NONE');
    return <AdminLayout title={`Landings: ${subject.title}`}><Head title={`Landings: ${subject.title}`}/><Link href={productUrl??`/admin/retos/${subject.slug}`} className="text-sm font-bold text-brand underline">← Volver al producto</Link>
        <section className="mt-6 rounded-[var(--radius-card)] border border-border bg-surface p-6"><p className="discovery-eyebrow text-brand">PRESENTACIÓN DE NAVEGACIÓN</p><h2 className="mt-2 text-2xl font-extrabold">{defaultItem?`Landing: “${defaultItem.name}”`:'Ficha del producto'}</h2><p className="mt-3 max-w-2xl text-sm text-muted-foreground">Visitantes: {defaultItem?'Landing':'Ficha del producto'}<br/>Usuarios con sesión: {defaultItem?.default_scope==='ALL'?'Landing':'Ficha del producto'}</p>{defaultItem&&<button className="mt-5 rounded-[var(--radius-control)] border border-border px-4 py-3 text-sm font-extrabold" onClick={()=>router.post(`${base}/default-product`)}>VOLVER A FICHA DEL PRODUCTO</button>}</section>
        <div className="mt-7 flex items-center justify-between"><h2 className="text-xl font-extrabold">PRESENTACIONES</h2><button className="rounded-[var(--radius-control)] bg-brand px-4 py-3 text-sm font-extrabold text-brand-foreground" onClick={()=>begin(null)}>CREAR LANDING</button></div>
        <div className="mt-4 space-y-4">{presentations.map(item=><article key={item.id} className="rounded-[var(--radius-card)] border border-border bg-surface p-5"><h3 className="text-lg font-extrabold">{item.name}</h3><p className="mt-1 text-sm text-muted-foreground">{item.status} · {item.default_scope} · /l/{item.slug}{item.campaign_key?` · ${item.campaign_key}`:''}</p><div className="mt-4 flex flex-wrap gap-3 text-sm font-bold"><button onClick={()=>begin(item)} className="underline">Editar</button><Link href={`${base}/${item.slug}/preview`} className="underline">Preview</Link>{item.status==='PUBLISHED'&&<Link href={`/l/${item.slug}`} className="underline">Vista pública</Link>}{item.status==='DRAFT'&&<button onClick={()=>router.post(`${base}/${item.slug}/publish`)} className="underline">PUBLICAR</button>}{item.status==='PUBLISHED'&&<><button onClick={()=>router.post(`${base}/${item.slug}/default`,{default_scope:'GUESTS'})} className="underline">USAR PARA VISITANTES</button><button onClick={()=>router.post(`${base}/${item.slug}/default`,{default_scope:'ALL'})} className="underline">USAR PARA TODOS</button></>}{item.status!=='ARCHIVED'&&<button onClick={()=>router.post(`${base}/${item.slug}/archive`)} className="underline">ARCHIVAR</button>}</div>{item.status==='PUBLISHED'&&<div className="mt-3 space-y-2 text-sm text-muted-foreground"><p>Usar para visitantes: Las personas que todavía no iniciaron sesión verán esta landing desde Home, Explorar y búsqueda. Los usuarios que ya iniciaron sesión seguirán viendo la ficha del producto.</p><p>Usar para todos: Todos los usuarios abrirán esta landing desde la navegación normal. Úsalo para lanzamientos o campañas donde quieras reemplazar temporalmente la ficha.</p></div>}</article>)}</div>
        {open&&<form className="mt-8 grid max-w-3xl gap-4 rounded-[var(--radius-card)] border border-border bg-surface p-6 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();const payload=Object.fromEntries(Object.entries(form).map(([key,value])=>[key,value.trim()||null]));editing?router.put(`${base}/${editing.slug}`,payload):router.post(base,payload);}}><h2 className="col-span-full text-xl font-extrabold">{editing?'EDITAR LANDING':'NUEVA LANDING'}</h2>{field('name','Nombre interno')}{field('slug','Slug único')}{field('campaign_key','Campaign key (opcional)')}{field('eyebrow','Eyebrow')}{field('headline','Headline editorial (sin cifras)')}{field('subheadline','Subheadline editorial (sin cifras)',true)}{field('hero_path','Referencia del visual')}{field('hero_alt','Descripción del visual')}{field('reward_display_override','Copy complementario del valor (sin cifras)')}{field('final_cta_headline','Titular del CTA final (sin cifras)')}<div className="col-span-full flex gap-3"><button className="rounded-[var(--radius-control)] bg-brand px-5 py-3 font-extrabold text-brand-foreground">GUARDAR</button><button type="button" className="px-4 font-bold underline" onClick={()=>setOpen(false)}>CANCELAR</button></div></form>}
    </AdminLayout>;
}
