import { FormEvent } from 'react';
import { Head, router } from '@inertiajs/react';
import PartnerLayout from '../layout';

export default function ContentForm({ partner, kind, item, locations }: any) {
    const benefit = kind === 'benefit'; const editable = !item || ['draft','changes_requested','rejected'].includes(item.review_status);
    const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); item ? router.post(`/partner/${partner.slug}/${benefit?'promociones':'experiencias'}/${item.slug}`, data, { headers: {'X-HTTP-Method-Override':'PUT'} }) : router.post(`/partner/${partner.slug}/${benefit?'promociones':'experiencias'}`, data); };
    const input = (name: string, label: string, type='text') => <label className="block text-sm">{label}<input disabled={!editable} name={name} type={type} defaultValue={item?.[name] ?? ''} className="mt-1 block w-full rounded border p-2"/></label>;
    return <PartnerLayout title={benefit?'Promoción':'Experiencia'} partner={partner}><Head title={benefit?'Promoción':'Experiencia'}/>{item?.review_notes && <p className="mb-4 rounded border border-amber-300 bg-amber-50 p-3">JAKAWI solicitó cambios: {item.review_notes}</p>}<form onSubmit={submit} className="space-y-3">{input('title','Título')}{input('short_description','Descripción corta')}<label className="block text-sm">Descripción<textarea disabled={!editable} name="description" defaultValue={item?.description ?? ''} className="mt-1 block w-full rounded border p-2"/></label>{input('category','Categoría')} {benefit ? <><label className="block text-sm">Alcance<select name="location_scope" defaultValue={item?.applies_to_all_locations?'all':'selected'} className="mt-1 block rounded border p-2"><option value="all">Todas las ubicaciones</option><option value="selected">Ubicaciones seleccionadas</option></select></label>{locations.map((l:any)=><label key={l.id} className="mr-4 text-sm"><input type="checkbox" name="location_ids[]" value={l.id} defaultChecked={item?.locations?.some((x:any)=>x.id===l.id)}/> {l.name}</label>)}{input('benefit_type','Tipo de beneficio')}{input('estimated_savings','Ahorro estimado','number')}</> : <><label className="block text-sm">Reservas<select name="reservation_method" defaultValue={item?.reservation_method ?? 'none'} className="mt-1 block rounded border p-2"><option value="none">No aplica</option><option value="whatsapp">WhatsApp</option><option value="url">URL</option><option value="phone">Teléfono</option><option value="external">Externo</option><option value="jakawi">JAKAWI</option></select></label>{input('experience_type','Tipo')}{input('duration_minutes','Duración (minutos)','number')}{input('regular_price','Precio regular','number')}{input('member_price','Precio miembro','number')}{input('reservation_whatsapp','WhatsApp')}{input('reservation_url','URL de reserva')}{input('reservation_phone','Teléfono de reserva')}<label className="block text-sm">Imagen<input disabled={!editable} type="file" name="image" className="mt-1 block"/></label><label className="block text-sm">Portada<input disabled={!editable} type="file" name="cover" className="mt-1 block"/></label></>} {editable && <button className="rounded bg-primary px-3 py-2 text-primary-foreground">Guardar borrador</button>}</form>{item && editable && <button onClick={()=>router.post(`/partner/${partner.slug}/${benefit?'promociones':'experiencias'}/${item.slug}/enviar`)} className="mt-4 rounded border px-3 py-2">Enviar a revisión</button>}{!benefit && item && <Sessions partner={partner} item={item} locations={locations} editable={editable}/>}</PartnerLayout>;
}
function SessionForm({partner,item,locations}:any) { return <form onSubmit={e=>{e.preventDefault(); router.post(`/partner/${partner.slug}/experiencias/${item.slug}/sessions`,new FormData(e.currentTarget));}} className="mt-6 space-y-2 rounded border p-4"><h2 className="font-semibold">Nueva sesión</h2><input required name="starts_at" type="datetime-local" className="rounded border p-2"/><input name="ends_at" type="datetime-local" className="ml-2 rounded border p-2"/><input name="capacity" type="number" placeholder="Capacidad" className="ml-2 rounded border p-2"/><select name="location_id" className="ml-2 rounded border p-2"><option value="">Sin ubicación</option>{locations.map((l:any)=><option value={l.id} key={l.id}>{l.name}</option>)}</select><button className="block rounded border px-3 py-2">Añadir sesión</button></form> }
function Sessions({partner,item,locations,editable}:any) { return <>{item.sessions?.map((session:any)=><form key={session.id} onSubmit={e=>{e.preventDefault(); router.post(`/partner/${partner.slug}/experiencias/${item.slug}/sessions/${session.id}`,new FormData(e.currentTarget),{headers:{'X-HTTP-Method-Override':'PUT'}})}} className="mt-4 space-y-2 rounded border p-4"><h2 className="font-semibold">Sesión</h2><input disabled={!editable} required name="starts_at" type="datetime-local" defaultValue={session.starts_at?.slice(0,16)} className="rounded border p-2"/><input disabled={!editable} name="ends_at" type="datetime-local" defaultValue={session.ends_at?.slice(0,16)} className="ml-2 rounded border p-2"/><input disabled={!editable} name="capacity" type="number" defaultValue={session.capacity ?? ''} className="ml-2 rounded border p-2"/><input disabled={!editable} name="venue_label" defaultValue={session.venue_label ?? ''} placeholder="Lugar" className="ml-2 rounded border p-2"/><select disabled={!editable} name="location_id" defaultValue={session.location_id ?? ''} className="ml-2 rounded border p-2"><option value="">Sin ubicación</option>{locations.map((l:any)=><option value={l.id} key={l.id}>{l.name}</option>)}</select>{editable&&<button className="block rounded border px-3 py-2">Guardar sesión</button>}</form>)}{editable&&<SessionForm partner={partner} item={item} locations={locations}/>}</> }
