import { Head, Link, router, usePage } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '../layout';
type Option = {id:number;name?:string;title?:string;partner_id?:number};
type Challenge = Record<string, any>;
export default function Form({challenge,partners=[],cities,benefits,partner,heroUrl}:{challenge:Challenge|null;partners?:Option[];cities:Option[];benefits:Option[];partner?:{id:number;name:string;slug:string};heroUrl?:string|null}) {
    const [image,setImage]=useState<File|null>(null);
    const {errors}=usePage().props as {errors:Record<string,string>};
    const [form,setForm]=useState<Record<string,any>>({title:challenge?.title??'',slug:challenge?.slug??'',description:challenge?.description??'',status:challenge?.status??'draft',partner_id:partner?.id??challenge?.partner_id??'',city_id:challenge?.city_id??'',starts_at:challenge?.starts_at?.slice(0,16)??'',ends_at:challenge?.ends_at?.slice(0,16)??'',allowed_platforms:(challenge?.allowed_platforms??[]).join(', '),required_hashtags:(challenge?.required_hashtags??[]).join(', '),required_mentions:(challenge?.required_mentions??[]).join(', '),published_from:challenge?.published_from?.slice(0,16)??'',published_until:challenge?.published_until?.slice(0,16)??'',evidence_type:challenge?.evidence_type??'SOCIAL_POST',qualification_type:challenge?.qualification_type??'VALID_EVIDENCE',evaluation_mode:challenge?.evaluation_mode??'CONTINUOUS',qualification_metric:challenge?.qualification_metric??'',qualification_target:challenge?.qualification_target??'',selection_type:challenge?.selection_type??'ALL_QUALIFIED',selection_metric:challenge?.selection_metric??'',winner_limit:challenge?.winner_limit??'',review_mode:challenge?.review_mode??'AUTOMATIC',participation_eligibility:challenge?.participation_eligibility??'ALL_USERS',reward_eligibility:challenge?.reward_eligibility??'ALL_USERS',max_entries_per_user:challenge?.max_entries_per_user??'',reward_type:challenge?.reward_type??'MANUAL_PRIZE',benefit_id:challenge?.benefit_id??'',manual_prize_description:challenge?.manual_prize_description??'',reward_jp_amount:challenge?.reward_jp_amount??'',instructions:challenge?.instructions??'',ranking_visibility:challenge?.ranking_visibility??'PUBLIC',ranking_refresh_interval_minutes:challenge?.ranking_refresh_interval_minutes??30});
    const set=(key:string,value:any)=>setForm(x=>({...x,[key]:value}));
    const input=(key:string,label:string,type='text')=><label className="flex flex-col gap-1">{label}<input className="rounded border p-2" type={type} value={form[key]} onChange={e=>set(key,e.target.value)}/>{errors[key]&&<span className="text-red-600">{errors[key]}</span>}</label>;
    const select=(key:string,label:string,options:string[][])=><label className="flex flex-col gap-1">{label}<select className="rounded border p-2" value={form[key]} onChange={e=>set(key,e.target.value)}>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select>{errors[key]&&<span className="text-red-600">{errors[key]}</span>}</label>;
    return <ChallengeLayout title={challenge?'Editar reto':'Crear reto'} partner={partner}><Link href={partner?`/partner/${partner.slug}/retos`:'/admin/retos'}>← Retos</Link><form className="mt-6 grid max-w-3xl gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const payload={...form,partner_id:form.partner_id||null,city_id:form.city_id||null,benefit_id:form.reward_type==='BENEFIT' ? form.benefit_id||null : null,manual_prize_description:form.reward_type==='MANUAL_PRIZE' ? form.manual_prize_description : null,reward_jp_amount:form.reward_type==='JP' ? form.reward_jp_amount||null : null,qualification_metric:form.qualification_metric||null,qualification_target:form.qualification_target||null,winner_limit:form.winner_limit||null,selection_metric:form.selection_metric||null,max_entries_per_user:form.max_entries_per_user||null,starts_at:form.starts_at||null,ends_at:form.ends_at||null,published_from:form.published_from||null,published_until:form.published_until||null,allowed_platforms:form.allowed_platforms.split(',').map((x:string)=>x.trim()).filter(Boolean),required_hashtags:form.required_hashtags.split(',').map((x:string)=>x.trim()).filter(Boolean),required_mentions:form.required_mentions.split(',').map((x:string)=>x.trim()).filter(Boolean)};partner ? (challenge ? router.put(`/partner/${partner.slug}/retos/${challenge.slug}`,payload) : router.post(`/partner/${partner.slug}/retos`,payload)) : (challenge ? router.put(`/admin/retos/${challenge.slug}`,payload) : router.post('/admin/retos',payload));}}>
        <h2 className="col-span-full mt-4 text-xl font-bold">1. EL RETO</h2>
        {input('title','Título')}{!partner&&input('slug','Dirección del reto')}{input('description','Descripción')}{!partner&&select('status','Publicación',[['draft','Borrador'],['open','Publicar o programar'],['closed','Cerrado'],['cancelled','Cancelado']])}
        {!partner&&select('partner_id','Partner',[['','JAKAWI'],...partners.map(p=>[String(p.id),p.name??''])])}{select('city_id','Ciudad',[['','Nacional'],...cities.map(c=>[String(c.id),c.name??''])])}
        <h2 className="col-span-full mt-4 text-xl font-bold">2. QUÉ DEBEN HACER</h2>
        {input('instructions','Instrucciones para participar')}{select('evidence_type','Tipo de participación',[['SOCIAL_POST','Publicación social'],['MANUAL','Presencial o manual']])}
        {form.evidence_type==='SOCIAL_POST'&&<>{input('allowed_platforms','Plataformas permitidas (separadas por coma)')}{input('required_hashtags','Etiquetas requeridas (separadas por coma)')}{input('required_mentions','Menciones requeridas (separadas por coma)')}{input('max_entries_per_user','Máximo de publicaciones por persona','number')}{input('published_from','Publicación válida desde','datetime-local')}{input('published_until','Publicación válida hasta','datetime-local')}</>}
        <h2 className="col-span-full mt-4 text-xl font-bold">3. CÓMO SE CUMPLE</h2>
        {select('qualification_type','Meta',[['VALID_EVIDENCE','Cumplir las reglas'],['METRIC_THRESHOLD','Llegar a una meta'],['MANUAL','Confirmación JAKAWI']])}{form.qualification_type==='METRIC_THRESHOLD'&&<>{select('qualification_metric','Métrica',[['','Elige una'],['views','Vistas'],['likes','Likes'],['comments','Comentarios']])}{input('qualification_target','Meta mínima','number')}</>}
        <h2 className="col-span-full mt-4 text-xl font-bold">4. CÓMO SE ELIGEN GANADORES</h2>
        {select('selection_type','Ganadores',[['ALL_QUALIFIED','Todos los que cumplan'],['FIRST_N','Los primeros N verificados'],['TOP_N','Las mejores N participaciones'],['MANUAL','Selección JAKAWI']])}{form.selection_type!=='ALL_QUALIFIED'&&input('winner_limit','Cantidad de premios','number')}{form.selection_type==='TOP_N'&&<>{select('selection_metric','Métrica del ranking',[['','Elige una'],['views','Vistas'],['likes','Likes'],['comments','Comentarios']])}{select('ranking_visibility','Quién puede ver el ranking',[['PUBLIC','Todas las personas'],['PARTICIPANTS_ONLY','Solo participantes'],['NONE','Sin ranking']])}{input('ranking_refresh_interval_minutes','Actualización del ranking (mínimo 15 min)','number')}</>}{select('evaluation_mode','Cuándo se evalúa',[['CONTINUOUS','Durante el reto'],['AT_CLOSE','Al cierre']])}{select('review_mode','Confirmación de JAKAWI',[['AUTOMATIC','Automática'],['REQUIRED','JAKAWI revisa ganadores']])}
        <h2 className="col-span-full mt-4 text-xl font-bold">5. PREMIO</h2>
        {select('reward_type','Premio',[['BENEFIT','Beneficio propio'],['MANUAL_PRIZE','Premio manual'],['JP','Puntos JP']])}{form.reward_type==='BENEFIT'&&select('benefit_id','Beneficio propio elegible',[['','Elige uno'],...benefits.filter(b=>!form.partner_id||b.partner_id===undefined||b.partner_id===Number(form.partner_id)).map(b=>[String(b.id),b.title??''])])}{form.reward_type==='MANUAL_PRIZE'&&input('manual_prize_description','Descripción del premio')}{form.reward_type==='JP'&&input('reward_jp_amount','JP otorgados','number')}
        <h2 className="col-span-full mt-4 text-xl font-bold">6. MEMBRESÍA</h2>
        {select('participation_eligibility','Quién puede participar',[['ALL_USERS','Cualquier usuario'],['ACTIVE_MEMBERS','Solo miembros activos']])}{select('reward_eligibility','Quién puede recibir el premio',[['ALL_USERS','Cualquier usuario'],['ACTIVE_MEMBERS','Solo miembros activos']])}
        <h2 className="col-span-full mt-4 text-xl font-bold">7. FECHAS</h2>
        {input('starts_at','Inicio','datetime-local')}{input('ends_at','Cierre','datetime-local')}
        <h2 className="col-span-full mt-4 text-xl font-bold">8. REVISIÓN Y PREVIEW</h2>
        <p className="col-span-full text-sm text-muted-foreground">Guarda el borrador y previsualiza la landing antes de enviarlo a JAKAWI.</p>
        <button className="rounded bg-primary px-4 py-2 text-primary-foreground">Guardar borrador</button>{partner&&challenge&&<Link className="rounded border px-4 py-2" href={`/partner/${partner.slug}/retos/${challenge.slug}/preview`}>PREVISUALIZAR LANDING</Link>}</form>{challenge&&<form className="mt-5 space-y-3" onSubmit={e=>{e.preventDefault();if(image)router.post(partner?`/partner/${partner.slug}/retos/${challenge.slug}/imagen`:`/admin/retos/${challenge.slug}/imagen`,{image},{forceFormData:true});}}><label className="block font-bold">Visual del reto<input type="file" accept="image/jpeg,image/png,image/webp" className="mt-2 block" onChange={e=>setImage(e.target.files?.[0]??null)}/></label>{heroUrl&&<img src={heroUrl} alt="Visual actual" className="h-36 w-64 rounded-xl object-cover"/>}<button type="submit" disabled={!image} className="rounded border px-4 py-2">GUARDAR VISUAL</button>{errors.image&&<p className="text-red-600">{errors.image}</p>}</form>}{partner&&challenge&&['DRAFT','CHANGES_REQUESTED'].includes(challenge.review_status)&&<button className="mt-5 rounded bg-brand px-5 py-3 font-bold text-brand-foreground" onClick={()=>router.post(`/partner/${partner.slug}/retos/${challenge.slug}/enviar`)}>ENVIAR A JAKAWI</button>}{partner&&challenge?.review_comment&&<p className="mt-4 rounded border p-4">Comentario de JAKAWI: {challenge.review_comment}</p>}</ChallengeLayout>;
}

function ChallengeLayout({partner,title,children}:{partner?:{name:string;slug:string};title:string;children:React.ReactNode}) { return partner?<main className="mx-auto max-w-4xl px-4 py-8"><Head title={title}/><p className="text-sm text-muted-foreground">{partner.name} · Retos</p><h1 className="mt-2 text-3xl font-bold">{title}</h1>{children}</main>:<AdminLayout title={title}>{children}</AdminLayout>; }
