import { Link, router, usePage } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '../layout';
type Option = {id:number;name?:string;title?:string;partner_id?:number};
type Challenge = Record<string, any>;
export default function Form({challenge,partners,cities,benefits}:{challenge:Challenge|null;partners:Option[];cities:Option[];benefits:Option[]}) {
    const {errors}=usePage().props as {errors:Record<string,string>};
    const [form,setForm]=useState<Record<string,any>>({title:challenge?.title??'',slug:challenge?.slug??'',description:challenge?.description??'',status:challenge?.status??'draft',partner_id:challenge?.partner_id??'',city_id:challenge?.city_id??'',starts_at:challenge?.starts_at?.slice(0,16)??'',ends_at:challenge?.ends_at?.slice(0,16)??'',allowed_platforms:(challenge?.allowed_platforms??[]).join(', '),required_hashtags:(challenge?.required_hashtags??[]).join(', '),required_mentions:(challenge?.required_mentions??[]).join(', '),published_from:challenge?.published_from?.slice(0,16)??'',published_until:challenge?.published_until?.slice(0,16)??'',qualification_mode:challenge?.qualification_mode??'VALID_POST',evaluation_mode:challenge?.evaluation_mode??'CONTINUOUS',metric:challenge?.metric??'',target:challenge?.target??'',winner_count:challenge?.winner_count??'',reward_type:challenge?.reward_type??'MANUAL_PRIZE',benefit_id:challenge?.benefit_id??'',manual_prize_description:challenge?.manual_prize_description??''});
    const set=(key:string,value:any)=>setForm(x=>({...x,[key]:value}));
    const input=(key:string,label:string,type='text')=><label className="flex flex-col gap-1">{label}<input className="rounded border p-2" type={type} value={form[key]} onChange={e=>set(key,e.target.value)}/>{errors[key]&&<span className="text-red-600">{errors[key]}</span>}</label>;
    const select=(key:string,label:string,options:string[][])=><label className="flex flex-col gap-1">{label}<select className="rounded border p-2" value={form[key]} onChange={e=>set(key,e.target.value)}>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select>{errors[key]&&<span className="text-red-600">{errors[key]}</span>}</label>;
    return <AdminLayout title={challenge?'Editar reto':'Crear reto'}><Link href="/admin/retos">← Retos</Link><form className="mt-6 grid max-w-3xl gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const payload={...form,partner_id:form.partner_id||null,city_id:form.city_id||null,benefit_id:form.benefit_id||null,metric:form.metric||null,target:form.target||null,winner_count:form.winner_count||null,starts_at:form.starts_at||null,ends_at:form.ends_at||null,published_from:form.published_from||null,published_until:form.published_until||null,allowed_platforms:form.allowed_platforms.split(',').map((x:string)=>x.trim()).filter(Boolean),required_hashtags:form.required_hashtags.split(',').map((x:string)=>x.trim()).filter(Boolean),required_mentions:form.required_mentions.split(',').map((x:string)=>x.trim()).filter(Boolean)};challenge?router.put(`/admin/retos/${challenge.slug}`,payload):router.post('/admin/retos',payload);}}>
        {input('title','Título')}{input('slug','Slug')}{input('description','Descripción')}{select('status','Estado',[['draft','Borrador'],['open','Abierto'],['closed','Cerrado'],['cancelled','Cancelado']])}
        {select('partner_id','Partner',[['','Ninguno'],...partners.map(p=>[String(p.id),p.name??''])])}{select('city_id','Ciudad',[['','Nacional'],...cities.map(c=>[String(c.id),c.name??''])])}
        {input('starts_at','Inicio','datetime-local')}{input('ends_at','Fin','datetime-local')}{input('allowed_platforms','Plataformas (coma)')}{input('required_hashtags','Hashtags (coma)')}{input('required_mentions','Menciones (coma)')}{input('published_from','Publicado desde','datetime-local')}{input('published_until','Publicado hasta','datetime-local')}
        {select('qualification_mode','Modo',[['VALID_POST','Publicación válida'],['METRIC_THRESHOLD','Umbral'],['RANKED','Ranking'],['MANUAL','Manual']])}{select('evaluation_mode','Evaluación',[['CONTINUOUS','Continua'],['AT_CLOSE','Al cierre']])}{select('metric','Métrica',[['','Ninguna'],['views','Vistas'],['likes','Me gusta'],['comments','Comentarios']])}{input('target','Objetivo','number')}{input('winner_count','Ganadores','number')}
        {select('reward_type','Premio',[['BENEFIT','Beneficio'],['MANUAL_PRIZE','Premio manual']])}{select('benefit_id','Beneficio exclusivo',[['','Ninguno'],...benefits.filter(b=>!form.partner_id||b.partner_id===Number(form.partner_id)).map(b=>[String(b.id),b.title??''])])}{input('manual_prize_description','Descripción del premio')}
        <button className="rounded bg-primary px-4 py-2 text-primary-foreground">Guardar reto</button></form></AdminLayout>;
}
