import { Link, router } from '@inertiajs/react';
import AdminLayout from '../layout';
type Entry={id:number;social_url:string;platform:string|null;views:number|null;likes:number|null;comments:number|null;validation_status:string;final_metric_value:number|null};
type Participation={id:number;user_name:string;qualification_status:string;selection_status:string;qualified_entry_id:number|null;selected_entry_id:number|null;review_status:string|null;social_entries:Entry[];selected_entry:Entry|null;grant?:{status:string;reward_type:string;jp_amount:number|null;jp_credit?:{reversal?:{id:number}|null}|null}|null};
export default function Show({challenge,participations,ranking}:{challenge:{slug:string;title:string;status:string;evidence_type:string;qualification_type:string;selection_type:string;review_mode:string;winner_limit:number|null};participations:Participation[];ranking:Array<{participation_id:number;position:number;value:number}>}) {
 const base=`/admin/retos/${challenge.slug}`;
 return <AdminLayout title={challenge.title}><div className="flex flex-wrap gap-3"><Link href={`${base}/editar`} className="underline">Editar</Link><Link href={`/retos/${challenge.slug}`} className="underline">Vista pública</Link>{challenge.evidence_type==='SOCIAL_POST'&&<button onClick={()=>router.post(`${base}/actualizar`)} className="rounded border px-3 py-1">Actualizar todas</button>}{challenge.status==='open'&&<button onClick={()=>router.post(`${base}/cerrar`)} className="rounded border px-3 py-1">Cerrar reto</button>}</div><p className="mt-4">Estado: {challenge.status} · Evidencia: {challenge.evidence_type} · Calificación: {challenge.qualification_type} · Selección: {challenge.selection_type}</p>{challenge.selection_type==='TOP_N'&&<section className="mt-6"><h2 className="font-bold">Candidatos del ranking</h2>{ranking.map(r=><p key={r.participation_id}>#{r.position} · Participación {r.participation_id} · {r.value}</p>)}</section>}
 <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr>{['Usuario','Entradas','Calificación','Selección','Mejor entrada','Premio','Acciones'].map(x=><th key={x} className="border p-2 text-left">{x}</th>)}</tr></thead><tbody>{participations.map(p=><tr key={p.id}><td className="border p-2">{p.user_name}</td><td className="border p-2">{p.social_entries.length}</td><td className="border p-2">{p.qualification_status}{p.qualified_entry_id&&` · #${p.qualified_entry_id}`}</td><td className="border p-2">{p.selection_status}{p.review_status&&` · ${p.review_status}`}</td><td className="border p-2">{p.selected_entry?<a href={p.selected_entry.social_url} target="_blank" rel="noreferrer" className="underline">#{p.selected_entry.id} · {p.selected_entry.final_metric_value??'—'}</a>:'—'}</td><td className="border p-2">{p.grant?`${p.grant.reward_type==='JP'?`${p.grant.jp_amount} JP`:p.grant.reward_type} · ${p.grant.status}${p.grant.jp_credit?.reversal?' · reverso':''}`:'—'}</td><td className="border p-2"><div className="flex flex-col gap-1"><Link href={`${base}/participaciones/${p.id}`} className="underline">Ver entradas</Link>{challenge.evidence_type==='SOCIAL_POST'&&<button onClick={()=>router.post(`${base}/participaciones/${p.id}/actualizar`)}>Actualizar</button>}{['approved','rejected'].map(decision=><button key={decision} onClick={()=>router.post(`${base}/participaciones/${p.id}/revisar`,{decision})}>{decision==='approved'?'Aprobar':'Rechazar'}</button>)}{(p.selection_status==='candidate'||challenge.selection_type==='MANUAL')&&!p.grant&&<button onClick={()=>router.post(`${base}/participaciones/${p.id}/ganador`)}>Confirmar candidato</button>}{p.qualification_status==='qualified'&&!p.grant&&challenge.selection_type!=='TOP_N'&&challenge.selection_type!=='MANUAL'&&<button onClick={()=>router.post(`${base}/participaciones/${p.id}/conceder`)}>Conceder premio</button>}{p.grant?.status==='granted'&&<button onClick={()=>router.post(`${base}/participaciones/${p.id}/cancelar-premio`)}>Cancelar premio</button>}{p.grant?.reward_type==='MANUAL_PRIZE'&&p.grant.status==='granted'&&<button onClick={()=>router.post(`${base}/participaciones/${p.id}/entregar`)}>Marcar entregado</button>}</div></td></tr>)}</tbody></table></div></AdminLayout>;
}
