import { Form, Link } from '@inertiajs/react';
import AdminLayout from '../layout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export default function Adjustments({ adjustments, filters, users, partners }: any) {
    return <AdminLayout title="Ajustes">
        <div className="mb-8 flex flex-wrap gap-2 text-sm">
            {['affiliates', 'conversions', 'rewards', 'payouts', 'attribution'].map((type) => <Link key={type} className="rounded border px-3 py-2" href={`/admin/exports/${type}`}>CSV {type}</Link>)}
        </div>
        <Form method="get" action="/admin/adjustments" className="mb-6 flex flex-wrap gap-2"><Input name="from" type="date" defaultValue={filters.from} /><Input name="to" type="date" defaultValue={filters.to} /><select name="type" defaultValue={filters.type ?? ''} className="rounded border px-2"><option value="">Todos los tipos</option><option value="ledger_credit">Crédito</option><option value="ledger_debit">Débito</option><option value="reward_status_correction">Estado</option><option value="attribution_correction">Atribución</option></select><Button>Filtrar</Button></Form>
        <section className="mb-8 rounded border p-4"><h2 className="font-semibold">Ajuste manual de ledger</h2><p className="mb-3 text-sm text-muted-foreground">CASH y JP se registran por separado; no modifica balances de usuario.</p><Form method="post" action="/admin/adjustments/ledger" className="grid max-w-2xl gap-3 sm:grid-cols-2"><select name="beneficiary_type" className="rounded border p-2"><option value="USER">Usuario</option><option value="PARTNER">Partner</option></select><Input name="beneficiary_id" type="number" placeholder="ID de beneficiario" required /><select name="unit" className="rounded border p-2"><option value="CASH">CASH</option><option value="JP">JP</option></select><Input name="amount" type="number" step="0.01" placeholder="Monto (+/-)" required /><textarea name="reason" required placeholder="Motivo obligatorio" className="min-h-20 rounded border p-2 sm:col-span-2" /><label className="text-sm sm:col-span-2"><input name="confirm" type="checkbox" value="1" required /> Confirmo este ajuste sensible e inmutable.</label><Button className="sm:w-fit">Registrar ajuste</Button></Form></section>
        <section className="mb-8 rounded border p-4"><h2 className="font-semibold">Corregir estado de recompensa</h2><Form method="post" action="/admin/adjustments/rewards/REWARD_ID/status" onSubmit={(event: any) => { const form = event.currentTarget; form.action = `/admin/adjustments/rewards/${form.reward_id.value}/status`; }} className="grid max-w-2xl gap-3 sm:grid-cols-2"><Input name="reward_id" type="number" placeholder="ID de recompensa" required /><select name="status" className="rounded border p-2"><option value="available">PENDING → AVAILABLE</option><option value="cancelled">AVAILABLE → CANCELLED</option></select><Input name="reason" placeholder="Motivo obligatorio" required className="sm:col-span-2" /><label className="text-sm sm:col-span-2"><input name="confirm" type="checkbox" value="1" required /> Confirmo la transición controlada.</label><Button className="sm:w-fit">Corregir estado</Button></Form><p className="mt-2 text-sm text-muted-foreground">PAID está protegido: use un ajuste financiero separado.</p></section>
        <section className="space-y-3"><h2 className="font-semibold">Historial inmutable</h2>{adjustments.data.map((a: any) => <article key={a.id} className="rounded border p-3 text-sm"><p><strong>{a.type}</strong> · {a.created_at} · admin: {a.actor?.name ?? a.actor_user_id}</p><p>Destino: {a.target_type ?? 'ledger'}:{a.target_id ?? `${a.beneficiary_type}:${a.beneficiary_id}`} · {a.amount} {a.unit}</p><p>Motivo: {a.reason}</p><p className="text-muted-foreground">Antes: {JSON.stringify(a.before)} · Después: {JSON.stringify(a.after)}</p></article>)}</section>
    </AdminLayout>;
}
