import { Link } from '@inertiajs/react';
import { JakawiImage } from '@/components/jakawi-image';
import { CalendarDays, MapPin } from 'lucide-react';
type Experience = { id: number; slug: string; destination_url?: string; title: string; image_url?: string | null; image_srcset?: Array<{ src: string; width: number }>; category?: string | null; sessions?: Array<{ starts_at?: string; location?: { name?: string } | null; venue_label?: string | null }> };
export default function ExperienceCard({ experience, variant = 'default' }: { experience: Experience; variant?: 'default' | 'discovery' | 'list' }) {
 const session = experience.sessions?.[0]; const when = session?.starts_at ? new Intl.DateTimeFormat('es-BO', { weekday: 'short', day: 'numeric', month: 'short' }).format(new Date(session.starts_at)) : 'Muy pronto';
 const list = variant === 'list';
 return <Link href={experience.destination_url ?? `/experiencias/${experience.slug}`} className={`group overflow-hidden border border-border bg-surface-elevated transition duration-200 active:scale-[.98] ${list ? 'grid min-h-36 grid-cols-[38%_1fr] rounded-[var(--radius-card)]' : `block w-[84vw] max-w-96 shrink-0 ${variant === 'discovery' ? 'rounded-[var(--radius-card)]' : 'rounded-[24px]'} sm:w-full`}`}><div className={`relative ${list ? 'min-h-full' : 'aspect-[16/10]'} bg-surface-muted`}><JakawiImage src={experience.image_url} srcset={experience.image_srcset} sizes={list ? '180px' : '(min-width: 768px) 33vw, 84vw'} alt={experience.title} className="h-full w-full object-cover" />{!list ? <span className="absolute top-3 left-3 rounded-full bg-surface px-3 py-1.5 text-xs font-extrabold tracking-[0.1em] text-foreground uppercase">Experiencia</span> : null}</div><div className={`${list ? 'flex min-w-0 flex-col justify-center p-[var(--space-card)]' : 'space-y-2 p-4'}`}><p className="discovery-eyebrow text-brand">Experiencia JAKAWI</p><h3 className="mt-1 text-xl leading-tight font-extrabold">{experience.title}</h3><p className="mt-2 flex items-center gap-1.5 text-sm font-semibold text-foreground-soft"><CalendarDays className="size-4 text-brand" />{when}</p><p className="mt-1 flex items-center gap-1.5 text-sm text-muted-foreground"><MapPin className="size-4" />{session?.location?.name ?? session?.venue_label ?? experience.category ?? 'JAKAWI'}</p></div></Link>;
}
