import { Head, Link, useForm } from '@inertiajs/react';

export default function CityLanding({ city, interestCount, interestRecorded }: { city: any; interestCount: number; interestRecorded: boolean }) {
    const form = useForm({});
    const paused = city.status === 'PAUSED';
    const activeCityHref = '/ciudades/cochabamba';

    return <main className="min-h-screen bg-background px-4 pt-[max(2rem,env(safe-area-inset-top))] pb-12 font-discovery text-foreground"><Head title={city.name} /><section className="mx-auto max-w-md"><Link href="/" className="text-sm font-bold tracking-[0.12em] text-brand uppercase">JAKAWI</Link><p className="mt-12 text-sm font-extrabold tracking-[0.16em] text-brand uppercase">{city.name}</p>{paused ? <><h1 className="mt-3 text-4xl leading-none font-extrabold tracking-tight">ESTAMOS EN PAUSA.</h1><p className="mt-6 text-base leading-7 text-muted-foreground">JAKAWI no está disponible temporalmente en {city.name}. Conservamos el interés de esta ciudad mientras preparamos los próximos pasos.</p></> : interestRecorded ? <><h1 className="mt-3 text-4xl leading-none font-extrabold tracking-tight">{city.name.toUpperCase()} ESTÁ MÁS CERCA</h1><p className="mt-6 text-base leading-7 text-muted-foreground">Ya registramos tu interés. Te avisaremos cuando haya novedades importantes.</p><Link href={activeCityHref} className="mt-8 flex min-h-13 items-center justify-center rounded-2xl bg-brand px-5 text-sm font-extrabold tracking-[0.08em] text-brand-foreground uppercase">Explorar Cochabamba</Link></> : <><h1 className="mt-3 text-4xl leading-none font-extrabold tracking-tight">JAKAWI ESTÁ LLEGANDO.</h1><p className="mt-6 text-base leading-7 text-muted-foreground">Estamos reuniendo los lugares, experiencias y personas que harán que valga la pena abrir JAKAWI aquí.</p>{interestCount > 0 ? <p className="mt-5 text-sm font-semibold">{interestCount} {interestCount === 1 ? 'persona ya quiere' : 'personas ya quieren'} JAKAWI en {city.name}</p> : null}<form onSubmit={(event) => { event.preventDefault(); form.post(`/ciudades/${city.slug}/interes`); }}><button className="mt-8 flex min-h-13 w-full items-center justify-center rounded-2xl bg-brand px-5 text-sm font-extrabold tracking-[0.08em] text-brand-foreground uppercase disabled:opacity-60" disabled={form.processing}>Quiero JAKAWI en {city.name}</button></form></>}<section className="mt-12 border-t border-border pt-8"><h2 className="text-sm font-extrabold tracking-[0.14em] uppercase">¿Tienes un negocio?</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Queremos conocer a los negocios que podrían ser partners fundadores cuando JAKAWI llegue a {city.name}.</p><p className="mt-4 text-sm font-bold text-muted-foreground">QUIERO SER PARTNER FUNDADOR · Próximamente</p></section>{paused ? <Link href={activeCityHref} className="mt-8 flex min-h-13 items-center justify-center rounded-2xl border border-border px-5 text-sm font-extrabold tracking-[0.08em] uppercase">Explorar Cochabamba</Link> : null}</section></main>;
}
