import { Link } from '@inertiajs/react';
import PartnerLayout from './layout';

type Kpis = { period: { days: number }; value: Record<string, number>; benefits: Record<string, number>; experiences: Record<string, number>; topBenefits: Array<{ title: string; redemptions: number; members: number; savings: number }>; topExperiences: Array<{ title: string; reservations: number; confirmed: number; checkins: number; people: number }>; discovery: Record<string, number>; trend: Array<{ label: string; redemptions: number; checkins: number }> };
const money = (n: number) => new Intl.NumberFormat('es-BO', { style: 'currency', currency: 'BOB', maximumFractionDigits: 0 }).format(n);

export default function Performance({ partner, kpis }: { partner: { name: string; slug: string }; kpis: Kpis }) {
    const max = Math.max(1, ...kpis.trend.flatMap((x) => [x.redemptions, x.checkins]));
    return <PartnerLayout title="Rendimiento" partner={partner}><div className="space-y-8">
        <section><p className="text-sm text-muted-foreground">Periodo</p><div className="mt-2 flex gap-2">{[7, 30, 90].map((days) => <Link key={days} href={`/partner/${partner.slug}/rendimiento?period=${days}`} className={`rounded-md border px-3 py-2 text-sm ${kpis.period.days === days ? 'bg-primary text-primary-foreground' : 'border-border'}`}>{days} días</Link>)}</div></section>
        <Section title="Valor"><Grid><Metric label="Miembros atendidos" value={kpis.value.members_served}/><Metric label="Miembros nuevos" value={kpis.value.new_members}/><Metric label="Miembros que regresaron" value={kpis.value.returning_members}/><Metric label="Tasa de retorno" value={`${kpis.value.return_rate}%`}/></Grid><p className="mt-3 text-xs text-muted-foreground">Un miembro atendido tuvo un canje confirmado o una asistencia registrada. La tasa compara quienes ya habían recibido valor antes del inicio del periodo.</p></Section>
        <Section title="Beneficios"><Grid><Metric label="Canjes confirmados" value={kpis.benefits.confirmed}/><Metric label="Valor entregado a miembros" value={money(kpis.benefits.savings)}/><Metric label="Vistas de beneficios" value={kpis.benefits.views}/><Metric label="Miembros que canjearon" value={kpis.benefits.unique_members}/><Metric label="Ahorro promedio por canje" value={money(kpis.benefits.average_savings)}/></Grid></Section>
        <Section title="Experiencias"><Grid><Metric label="Solicitudes de reserva" value={kpis.experiences.requests}/><Metric label="Reservas confirmadas" value={kpis.experiences.confirmed}/><Metric label="Asistencias" value={kpis.experiences.checkins}/><Metric label="Personas asistentes" value={kpis.experiences.people}/><Metric label="Tasa de asistencia" value={`${kpis.experiences.attendance_rate}%`}/></Grid></Section>
        <Section title="Actividad JAKAWI"><div className="rounded-md border border-border bg-surface p-4">{kpis.trend.length ? <div className="flex h-40 items-end gap-2">{kpis.trend.map((x) => <div key={x.label} className="flex min-w-5 flex-1 flex-col items-center justify-end gap-1 text-[10px]"><span>{x.redemptions + x.checkins}</span><div className="flex w-full items-end gap-px"><i className="w-1/2 bg-primary" style={{ height: `${x.redemptions / max * 100}%` }}/><i className="w-1/2 bg-emerald-500" style={{ height: `${x.checkins / max * 100}%` }}/></div><span className="truncate">{x.label.slice(-5)}</span></div>)}</div> : <p className="text-sm text-muted-foreground">Sin actividad confirmada en este periodo.</p>}<p className="mt-3 text-xs text-muted-foreground">Azul: canjes confirmados · verde: asistencias</p></div></Section>
        <Content title="Promociones destacadas" empty="Aún no hay canjes confirmados." rows={kpis.topBenefits} render={(x) => <><strong>{x.title}</strong><span>{x.redemptions} canjes · {x.members} miembros · {money(x.savings)}</span></>}/>
        <Content title="Experiencias destacadas" empty="Aún no hay reservas." rows={kpis.topExperiences} render={(x) => <><strong>{x.title}</strong><span>{x.reservations} reservas · {x.confirmed} confirmadas · {x.checkins} asistencias · {x.people} personas</span></>}/>
        <Section title="Descubrimiento y acciones"><Grid><Metric label="Vistas del perfil" value={kpis.discovery.partner_views}/><Metric label="Vistas de beneficios" value={kpis.discovery.benefit_views}/><Metric label="Vistas de experiencias" value={kpis.discovery.experience_views}/><Metric label="Clics en mapa" value={kpis.discovery.maps_clicks}/><Metric label="Clics en WhatsApp" value={kpis.discovery.whatsapp_clicks}/><Metric label="Clics para reservar" value={kpis.discovery.reserve_clicks}/></Grid><p className="mt-3 text-xs text-muted-foreground">Conteos de eventos registrados por JAKAWI; un clic de reserva externa no confirma una reserva.</p></Section>
    </div></PartnerLayout>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-lg font-semibold">{title}</h2><div className="mt-3">{children}</div></section>; }
function Grid({ children }: { children: React.ReactNode }) { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{children}</div>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-md border border-border bg-surface p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>; }
function Content<T extends { title: string }>({ title, rows, empty, render }: { title: string; rows: T[]; empty: string; render: (row: T) => React.ReactNode }) { return <Section title={title}>{rows.some((x: any) => x.redemptions || x.reservations) ? <div className="divide-y rounded-md border border-border">{rows.filter((x: any) => x.redemptions || x.reservations).map((x) => <div key={x.title} className="flex flex-col gap-1 p-4 text-sm [&_span]:text-muted-foreground">{render(x)}</div>)}</div> : <p className="text-sm text-muted-foreground">{empty}</p>}</Section>; }
