<?php

use App\Http\Controllers\AdminContentReviewController;
use App\Http\Controllers\AdminCityController;
use App\Http\Controllers\AdminExpansionController;
use App\Http\Controllers\AdminAffiliateController;
use App\Http\Controllers\AffiliateDashboardController;
use App\Http\Controllers\CreatorDashboardController;
use App\Http\Controllers\AdminCreatorController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdminRewardRuleController;
use App\Http\Controllers\AdminCampaignController;
use App\Http\Controllers\ExternalRedirectController;
use App\Http\Controllers\PublicJourneyLandingController;
use App\Http\Controllers\AdminSalesController;
use App\Http\Controllers\AdminPayoutController;
use App\Http\Controllers\AdminAdjustmentController;
use App\Http\Controllers\AdminExportController;
use App\Http\Controllers\ExperienceCheckInController;
use App\Http\Controllers\ExperienceReservationController;
use App\Http\Controllers\MemberProfileController;
use App\Http\Controllers\MembershipController;
use App\Http\Controllers\MembershipOfferController;
use App\Http\Controllers\AdminMembershipRequestController;
use App\Http\Controllers\PartnerContentController;
use App\Http\Controllers\PartnerLoginController;
use App\Http\Controllers\PartnerPortalController;
use App\Http\Controllers\PartnerReservationController;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\PublicJourneyIntentController;
use App\Http\Controllers\SelectedCityController;
use App\Http\Controllers\CityLandingController;
use App\Http\Controllers\PartnerApplicationController;
use App\Http\Controllers\PartnersLandingController;
use App\Http\Controllers\AdminPartnerApplicationController;
use App\Http\Controllers\AdminProgramApplicationController;
use App\Http\Controllers\AdminOwnershipAssignmentController;
use App\Http\Controllers\ProgramApplicationController;
use App\Http\Controllers\PromoterSalesController;
use App\Http\Controllers\RedemptionController;
use App\Http\Controllers\ReferralController;
use App\Http\Controllers\UnlockController;
use App\Http\Controllers\AdminUnlockController;
use App\Http\Controllers\PartnerUnlockController;
use App\Http\Controllers\OpportunityAnalyticsController;
use App\Http\Controllers\SocialChallengeController;
use App\Http\Controllers\AdminSocialChallengeController;
use App\Support\PublicJourneyConfig;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/', [PublicController::class, 'home'])->name('home');
Route::get('/membresia', [MembershipOfferController::class, 'show'])->name('membership.show');
Route::get('/membresia/registro', [MembershipOfferController::class, 'register'])->middleware('guest')->name('membership.register');
Route::get('/go/{slug}', [ExternalRedirectController::class, 'show'])->where('slug', '[a-z0-9]+(?:-[a-z0-9]+)*')->name('external-redirect.show');
Route::post('/analytics/public-landings/{key}/cta', [PublicJourneyLandingController::class, 'cta'])->where('key', '[a-z0-9]+(?:-[a-z0-9]+)*')->middleware('throttle:60,1')->name('public-landings.cta');
Route::get('/r/{code}', [ReferralController::class, 'open'])->where('code', '[A-Za-z0-9_-]+')->name('referrals.open');
Route::get('/r/{code}/d/{unlock:slug}', [ReferralController::class, 'unlock'])->where('code', '[A-Za-z0-9_-]+')->name('referrals.unlock');
Route::get('/explorar', [PublicController::class, 'explore'])->name('explore');
Route::get('/retos', [SocialChallengeController::class, 'index'])->name('social-challenges.index');
Route::get('/retos/{challenge:slug}', [SocialChallengeController::class, 'show'])->name('social-challenges.show');
Route::post('/retos/{challenge:slug}/participar', [SocialChallengeController::class, 'intent'])->name('social-challenges.intent');
Route::get('/partners', [PartnersLandingController::class, 'show'])->name('partners.index');
Route::get('/partners/aplicar', [PartnersLandingController::class, 'apply'])->name('partners.apply');
Route::get('/{program}', [ProgramApplicationController::class, 'show'])->whereIn('program', ['afiliados', 'creadores', 'promotores'])->name('programs.show');
Route::get('/{program}/aplicar', [ProgramApplicationController::class, 'apply'])->whereIn('program', ['afiliados', 'creadores', 'promotores'])->name('programs.apply');
Route::post('/analytics/opportunities', [OpportunityAnalyticsController::class, 'store'])->middleware('throttle:120,1')->name('analytics.opportunities.store');
Route::post('/analytics/journey-intent/{journey}/{slug}', [PublicJourneyIntentController::class, 'store'])->whereIn('journey', ['experience', 'unlock', 'benefit'])->middleware('throttle:60,1')->name('analytics.journey-intent.store');
Route::get('/ciudades/{city:slug}', [CityLandingController::class, 'show'])->name('cities.show');
Route::post('/ciudades/{city:slug}/interes', [CityLandingController::class, 'interest'])->middleware('throttle:20,1')->name('cities.interest');
Route::get('/ciudades/{city:slug}/partner', [PartnerApplicationController::class, 'create'])->name('cities.partner.create');
Route::post('/ciudades/{city:slug}/partner', [PartnerApplicationController::class, 'store'])->middleware('throttle:20,1')->name('cities.partner.store');
Route::get('/ciudades/{city:slug}/partner/recibida', [PartnerApplicationController::class, 'success'])->name('cities.partner.success');
Route::post('/ciudades/{city:slug}/seleccionar', [SelectedCityController::class, 'store'])->name('cities.select');
Route::get('/d/{unlock:slug}', [UnlockController::class, 'show'])->name('unlocks.show');
Route::post('/d/{unlock:slug}/shared', [UnlockController::class, 'share'])->name('unlocks.shared');
Route::get('/partners/{partner:slug}', [PublicController::class, 'partners'])->name('partners.show');
Route::get('/partners/{partner:slug}/whatsapp', [PublicController::class, 'partnerWhatsapp'])->name('partners.whatsapp');
Route::get('/lugares/{location:slug}', [PublicController::class, 'location'])->name('locations.show');
Route::get('/lugares/{location:slug}/mapa', [PublicController::class, 'map'])->name('locations.map');
Route::get('/lugares/{location:slug}/whatsapp', [PublicController::class, 'locationWhatsapp'])->name('locations.whatsapp');
Route::get('/beneficios', [PublicController::class, 'benefits'])->name('benefits.index');
Route::get('/beneficios/{benefit:slug}', [PublicController::class, 'benefit'])->name('benefits.show');
Route::get('/experiencias', [PublicController::class, 'experiences'])->name('experiences.index');
Route::get('/experiencias/{experience:slug}', [PublicController::class, 'experience'])->name('experiences.show');
Route::get('/experiencias/{experience:slug}/reservar', [PublicController::class, 'reserve'])->name('experiences.reserve');
Route::get('/partner/login', [PartnerLoginController::class, 'create'])->middleware('guest')->name('partner.login');
Route::post('/partner/login', [PartnerLoginController::class, 'store'])->middleware('guest')->name('partner.login.store');
Route::get('/partner/{partner:slug}/canjes/{redemption_public_id}', [RedemptionController::class, 'scan'])->middleware('signed')->name('partner.redemptions.scan');
Route::post('/partner/{partner:slug}/canjes/{redemption_public_id}', [RedemptionController::class, 'scanConfirm'])->middleware(['auth', 'verified', 'partner', 'signed'])->name('partner.redemptions.scan.confirm');
Route::get('/partner/{partner:slug}/asistencias/{reservation_public_id}', [ExperienceCheckInController::class, 'scan'])->middleware('signed')->name('partner.checkins.scan');
Route::middleware(['auth', 'verified', 'partner'])->group(function () {
    Route::get('/partner', [PartnerPortalController::class, 'index'])->name('partner.index');
    Route::get('/partner/reservas', fn (Request $request) => app(PartnerPortalController::class)->redirectToSinglePartner($request, 'partner.reservations.index'));
    Route::get('/validar', fn (Request $request) => app(PartnerPortalController::class)->redirectToSinglePartner($request, 'redemptions.validate'));
    Route::get('/partner/{partner:slug}', [PartnerPortalController::class, 'show'])->name('partner.portal.show');
    Route::post('/partner/{partner:slug}/payouts', [PartnerPortalController::class, 'requestPayout'])->name('partner.payouts.store');
    Route::get('/partner/{partner:slug}/desbloqueos', [PartnerUnlockController::class, 'index'])->name('partner.unlocks.index');
    Route::get('/partner/{partner:slug}/desbloqueos/crear', [PartnerUnlockController::class, 'form'])->name('partner.unlocks.create');
    Route::post('/partner/{partner:slug}/desbloqueos', [PartnerUnlockController::class, 'save'])->name('partner.unlocks.store');
    Route::get('/partner/{partner:slug}/desbloqueos/{unlock:slug}/editar', [PartnerUnlockController::class, 'form'])->name('partner.unlocks.edit');
    Route::put('/partner/{partner:slug}/desbloqueos/{unlock:slug}', [PartnerUnlockController::class, 'save'])->name('partner.unlocks.update');
    Route::post('/partner/{partner:slug}/desbloqueos/{unlock:slug}/enviar', [PartnerUnlockController::class, 'submit'])->name('partner.unlocks.submit');
    Route::post('/partner/{partner:slug}/desbloqueos/{unlock:slug}/participaciones/{participation}/cumplir', [PartnerUnlockController::class, 'fulfill'])->name('partner.unlocks.fulfill');
    Route::get('/partner/{partner:slug}/rendimiento', [PartnerPortalController::class, 'performance'])->name('partner.performance');
    Route::get('/partner/{partner:slug}/reservas', [PartnerReservationController::class, 'index'])->name('partner.reservations.index');
    Route::post('/partner/{partner:slug}/reservas/{reservation_public_id}/{status}', [PartnerReservationController::class, 'respond'])->whereIn('status', ['confirmed', 'rejected'])->name('partner.reservations.respond');
    Route::get('/partner/{partner:slug}/asistencias', [ExperienceCheckInController::class, 'form'])->name('partner.checkins.form');
    Route::post('/partner/{partner:slug}/asistencias', [ExperienceCheckInController::class, 'find'])->middleware('throttle:20,1')->name('partner.checkins.find');
    Route::post('/partner/{partner:slug}/asistencias/{reservation_public_id}', [ExperienceCheckInController::class, 'confirm'])->name('partner.checkins.confirm');
    Route::get('/partner/{partner:slug}/validar', [RedemptionController::class, 'form'])->name('redemptions.validate');
    Route::post('/partner/{partner:slug}/validar', [RedemptionController::class, 'confirm'])->middleware('throttle:20,1');
    Route::get('/partner/{partner:slug}/promociones', [PartnerContentController::class, 'benefits'])->name('partner.benefits.index');
    Route::get('/partner/{partner:slug}/promociones/crear', [PartnerContentController::class, 'benefitForm'])->name('partner.benefits.create');
    Route::post('/partner/{partner:slug}/promociones', [PartnerContentController::class, 'saveBenefit'])->name('partner.benefits.store');
    Route::get('/partner/{partner:slug}/promociones/{benefit:slug}/editar', [PartnerContentController::class, 'benefitForm'])->name('partner.benefits.edit');
    Route::put('/partner/{partner:slug}/promociones/{benefit:slug}', [PartnerContentController::class, 'saveBenefit'])->name('partner.benefits.update');
    Route::post('/partner/{partner:slug}/promociones/{benefit:slug}/enviar', [PartnerContentController::class, 'submitBenefit'])->name('partner.benefits.submit');
    Route::get('/partner/{partner:slug}/experiencias', [PartnerContentController::class, 'experiences'])->name('partner.experiences.index');
    Route::get('/partner/{partner:slug}/experiencias/crear', [PartnerContentController::class, 'experienceForm'])->name('partner.experiences.create');
    Route::post('/partner/{partner:slug}/experiencias', [PartnerContentController::class, 'saveExperience'])->name('partner.experiences.store');
    Route::get('/partner/{partner:slug}/experiencias/{experience:slug}/editar', [PartnerContentController::class, 'experienceForm'])->name('partner.experiences.edit');
    Route::put('/partner/{partner:slug}/experiencias/{experience:slug}', [PartnerContentController::class, 'saveExperience'])->name('partner.experiences.update');
    Route::post('/partner/{partner:slug}/experiencias/{experience:slug}/sessions', [PartnerContentController::class, 'saveSession'])->name('partner.experiences.sessions.store');
    Route::put('/partner/{partner:slug}/experiencias/{experience:slug}/sessions/{session}', [PartnerContentController::class, 'updateSession'])->name('partner.experiences.sessions.update');
    Route::post('/partner/{partner:slug}/experiencias/{experience:slug}/enviar', [PartnerContentController::class, 'submitExperience'])->name('partner.experiences.submit');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::post('/retos/{challenge:slug}/publicaciones', [SocialChallengeController::class, 'submit'])->middleware('throttle:10,1')->name('social-challenges.submit');
    Route::post('/retos/{challenge:slug}/actualizar', [SocialChallengeController::class, 'refresh'])->name('social-challenges.refresh');
    Route::post('/membresia/solicitar', [MembershipOfferController::class, 'request'])->middleware('throttle:20,1')->name('membership.request');
    Route::post('/membresia/volver/{purchaseRequest}', [MembershipOfferController::class, 'returnToIntent'])->name('membership.return');
    Route::post('/{program}/solicitudes', [ProgramApplicationController::class, 'store'])->whereIn('program', ['afiliados', 'creadores', 'promotores'])->middleware('throttle:20,1')->name('programs.applications.store');
    Route::get('dashboard', fn () => to_route('home'))->name('dashboard');
    Route::get('mi-jakawi', [MembershipController::class, 'show'])->name('mi-jakawi');
    Route::post('mi-jakawi/referral-shared', [MembershipController::class, 'shared'])->name('mi-jakawi.referral-shared');
    Route::get('perfil', [MemberProfileController::class, 'show'])->name('consumer.profile');
    Route::get('mi-jakawi/perfil', [MemberProfileController::class, 'show'])->name('member.profile.show');
    Route::put('mi-jakawi/perfil', [MemberProfileController::class, 'update'])->name('member.profile.update');
    Route::post('/experiencias/{experience:slug}/reservas', [ExperienceReservationController::class, 'store'])->name('experiences.reservations.store');
    Route::post('/reservas/{reservation:public_id}/cancelar', [ExperienceReservationController::class, 'cancel'])->name('experiences.reservations.cancel');
    Route::post('/beneficios/{benefit:slug}/canjear', [RedemptionController::class, 'start'])->name('redemptions.start');
    Route::post('/d/{unlock:slug}/interes', [UnlockController::class, 'interest'])->name('unlocks.interest');
    Route::post('/d/{unlock:slug}/comprometer', [UnlockController::class, 'commit'])->name('unlocks.commit');
    Route::post('/d/{unlock:slug}/cancelar', [UnlockController::class, 'cancel'])->name('unlocks.cancel');
    Route::post('/d/{unlock:slug}/confirmar', [UnlockController::class, 'confirm'])->name('unlocks.confirm');
    Route::get('/canjes/{redemption:public_id}', [RedemptionController::class, 'show'])->name('redemptions.show');
});

Route::middleware(['auth', 'verified', 'promoter'])->prefix('promoter')->group(function () {
    Route::get('sales', [PromoterSalesController::class, 'index'])->name('promoter.sales.index');
    Route::get('sales/create', [PromoterSalesController::class, 'create'])->name('promoter.sales.create');
    Route::post('sales', [PromoterSalesController::class, 'store'])->middleware('throttle:20,1')->name('promoter.sales.store');
    Route::get('sales/{purchase}', [PromoterSalesController::class, 'show'])->name('promoter.sales.show');
});

Route::middleware(['auth', 'verified', 'affiliate'])->prefix('affiliate')->group(function () {
    Route::get('/', [AffiliateDashboardController::class, 'show'])->name('affiliate.dashboard');
    Route::post('shared', [AffiliateDashboardController::class, 'shared'])->name('affiliate.shared');
    Route::post('payouts', [AffiliateDashboardController::class, 'requestPayout'])->name('affiliate.payouts.store');
});
Route::middleware(['auth', 'verified', 'creator'])->prefix('creator')->group(function () {
    Route::get('/', [CreatorDashboardController::class, 'show'])->name('creator.dashboard');
    Route::post('shared', [CreatorDashboardController::class, 'shared'])->name('creator.shared');
    Route::post('payouts', [CreatorDashboardController::class, 'requestPayout'])->name('creator.payouts.store');
});

Route::middleware(['auth', 'verified', 'admin'])->prefix('admin')->group(function () {
    Route::get('retos', [AdminSocialChallengeController::class, 'index'])->name('admin.social-challenges.index');
    Route::get('retos/crear', [AdminSocialChallengeController::class, 'form'])->name('admin.social-challenges.create');
    Route::post('retos', [AdminSocialChallengeController::class, 'save'])->name('admin.social-challenges.store');
    Route::get('retos/{challenge:slug}', [AdminSocialChallengeController::class, 'show'])->name('admin.social-challenges.show');
    Route::get('retos/{challenge:slug}/editar', [AdminSocialChallengeController::class, 'form'])->name('admin.social-challenges.edit');
    Route::put('retos/{challenge:slug}', [AdminSocialChallengeController::class, 'save'])->name('admin.social-challenges.update');
    Route::post('retos/{challenge:slug}/actualizar', [AdminSocialChallengeController::class, 'refresh'])->name('admin.social-challenges.refresh');
    Route::post('retos/{challenge:slug}/participaciones/{participation}/actualizar', [AdminSocialChallengeController::class, 'refresh'])->name('admin.social-challenges.participations.refresh');
    Route::get('retos/{challenge:slug}/participaciones/{participation}', [AdminSocialChallengeController::class, 'participation'])->name('admin.social-challenges.participations.show');
    Route::post('retos/{challenge:slug}/cerrar', [AdminSocialChallengeController::class, 'close'])->name('admin.social-challenges.close');
    Route::post('retos/{challenge:slug}/participaciones/{participation}/revisar', [AdminSocialChallengeController::class, 'review'])->name('admin.social-challenges.review');
    Route::post('retos/{challenge:slug}/participaciones/{participation}/ganador', [AdminSocialChallengeController::class, 'winner'])->name('admin.social-challenges.winner');
    Route::post('retos/{challenge:slug}/participaciones/{participation}/entregar', [AdminSocialChallengeController::class, 'fulfill'])->name('admin.social-challenges.fulfill');
    Route::post('retos/{challenge:slug}/participaciones/{participation}/conceder', [AdminSocialChallengeController::class, 'grant'])->name('admin.social-challenges.grant');
    Route::post('retos/{challenge:slug}/participaciones/{participation}/cancelar-premio', [AdminSocialChallengeController::class, 'cancelGrant'])->name('admin.social-challenges.grant.cancel');
    Route::get('solicitudes-membresia', [AdminMembershipRequestController::class, 'index'])->name('admin.membership-requests.index');
    Route::get('solicitudes-membresia/{purchaseRequest}', [AdminMembershipRequestController::class, 'show'])->name('admin.membership-requests.show');
    Route::post('ownership/{targetType}/{targetId}', [AdminOwnershipAssignmentController::class, 'save'])->whereNumber('targetId')->name('admin.ownership.save');
    Route::delete('ownership/{targetType}/{targetId}', [AdminOwnershipAssignmentController::class, 'remove'])->whereNumber('targetId')->name('admin.ownership.remove');
    Route::get('/', [AdminController::class, 'index'])->name('admin.index');
    Route::get('expansion', [AdminExpansionController::class, 'index'])->name('admin.expansion.index');
    Route::get('ciudades', [AdminCityController::class, 'index'])->name('admin.cities.index');
    Route::get('ciudades/crear', [AdminCityController::class, 'create'])->name('admin.cities.create');
    Route::post('ciudades', [AdminCityController::class, 'store'])->name('admin.cities.store');
    Route::get('ciudades/{city}', [AdminCityController::class, 'show'])->name('admin.cities.show');
    Route::get('ciudades/{city}/editar', [AdminCityController::class, 'edit'])->name('admin.cities.edit');
    Route::put('ciudades/{city}', [AdminCityController::class, 'update'])->name('admin.cities.update');
    Route::post('ciudades/{city}/estado', [AdminCityController::class, 'updateStatus'])->name('admin.cities.status.update');
    Route::get('solicitudes-partner', [AdminPartnerApplicationController::class, 'index'])->name('admin.partner-applications.index');
    Route::get('solicitudes-programas', [AdminProgramApplicationController::class, 'index'])->name('admin.program-applications.index');
    Route::get('solicitudes-programas/{programApplication}', [AdminProgramApplicationController::class, 'show'])->name('admin.program-applications.show');
    Route::post('solicitudes-programas/{programApplication}/estado', [AdminProgramApplicationController::class, 'status'])->name('admin.program-applications.status');
    Route::get('solicitudes-partner/{partnerApplication}', [AdminPartnerApplicationController::class, 'show'])->name('admin.partner-applications.show');
    Route::post('solicitudes-partner/{partnerApplication}/estado', [AdminPartnerApplicationController::class, 'status'])->name('admin.partner-applications.status');
    Route::get('desbloqueos', [AdminUnlockController::class, 'index'])->name('admin.unlocks.index');
    Route::get('desbloqueos/crear', [AdminUnlockController::class, 'form'])->name('admin.unlocks.create');
    Route::post('desbloqueos', [AdminUnlockController::class, 'save'])->name('admin.unlocks.store');
    Route::get('desbloqueos/{unlock:slug}/editar', [AdminUnlockController::class, 'form'])->name('admin.unlocks.edit');
    Route::put('desbloqueos/{unlock:slug}', [AdminUnlockController::class, 'save'])->name('admin.unlocks.update');
    Route::post('desbloqueos/{unlock:slug}/estado', [AdminUnlockController::class, 'transition'])->name('admin.unlocks.transition');
    Route::post('desbloqueos/{unlock:slug}/extender', [AdminUnlockController::class, 'extend'])->name('admin.unlocks.extend');
    Route::post('desbloqueos/{unlock:slug}/cerrar-compromisos', [AdminUnlockController::class, 'closeEarly'])->name('admin.unlocks.close-early');
    Route::post('desbloqueos/{unlock:slug}/participaciones/{participation}/retirar', [AdminUnlockController::class, 'remove'])->name('admin.unlocks.remove');
    Route::post('desbloqueos/{unlock:slug}/participaciones/{participation}/liberar-jp', [AdminUnlockController::class, 'releaseJp'])->name('admin.unlocks.release-jp');
    Route::post('desbloqueos/{unlock:slug}/participaciones/{participation}/corregir', [AdminUnlockController::class, 'correctParticipation'])->name('admin.unlocks.correct');
    Route::post('desbloqueos/{unlock:slug}/participaciones/{participation}/cumplir', [AdminUnlockController::class, 'fulfill'])->name('admin.unlocks.fulfill');
    Route::get('review', [AdminContentReviewController::class, 'index'])->name('admin.review.index');
    Route::post('review/benefits/{benefit}', [AdminContentReviewController::class, 'benefit'])->name('admin.review.benefit');
    Route::post('review/experiences/{experience}', [AdminContentReviewController::class, 'experience'])->name('admin.review.experience');
    Route::get('partners', [AdminController::class, 'partners'])->name('admin.partners.index');
    Route::get('partners/create', [AdminController::class, 'partnerForm'])->name('admin.partners.create');
    Route::post('partners', [AdminController::class, 'savePartner'])->name('admin.partners.store');
    Route::get('partners/{partner}/edit', [AdminController::class, 'partnerForm'])->name('admin.partners.edit');
    Route::put('partners/{partner}', [AdminController::class, 'savePartner'])->name('admin.partners.update');
    Route::post('partners/{partner}/referral-code', [AdminController::class, 'partnerReferralCode'])->name('admin.partners.referral-code');
    Route::get('locations', [AdminController::class, 'locations'])->name('admin.locations.index');
    Route::get('locations/create', [AdminController::class, 'locationForm'])->name('admin.locations.create');
    Route::post('locations', [AdminController::class, 'saveLocation'])->name('admin.locations.store');
    Route::get('locations/{location}/edit', [AdminController::class, 'locationForm'])->name('admin.locations.edit');
    Route::put('locations/{location}', [AdminController::class, 'saveLocation'])->name('admin.locations.update');
    Route::get('benefits', [AdminController::class, 'benefits'])->name('admin.benefits.index');
    Route::get('benefits/create', [AdminController::class, 'benefitForm'])->name('admin.benefits.create');
    Route::post('benefits', [AdminController::class, 'saveBenefit'])->name('admin.benefits.store');
    Route::get('benefits/{benefit}/edit', [AdminController::class, 'benefitForm'])->name('admin.benefits.edit');
    Route::put('benefits/{benefit}', [AdminController::class, 'saveBenefit'])->name('admin.benefits.update');
    Route::get('experiences', [AdminController::class, 'experiences'])->name('admin.experiences.index');
    Route::get('experiences/create', [AdminController::class, 'experienceForm'])->name('admin.experiences.create');
    Route::post('experiences', [AdminController::class, 'saveExperience'])->name('admin.experiences.store');
    Route::get('experiences/{experience}/edit', [AdminController::class, 'experienceForm'])->name('admin.experiences.edit');
    Route::put('experiences/{experience}', [AdminController::class, 'saveExperience'])->name('admin.experiences.update');
    Route::post('experiences/{experience}/sessions', [AdminController::class, 'sessions'])->name('admin.experiences.sessions.store');
    Route::put('experiences/{experience}/sessions/{session}', [AdminController::class, 'updateSession'])->name('admin.experiences.sessions.update');
    Route::delete('experiences/{experience}/sessions/{session}', [AdminController::class, 'deleteSession'])->name('admin.experiences.sessions.destroy');
    Route::get('memberships', [AdminController::class, 'memberships'])->name('admin.memberships.index');
    Route::post('memberships', [AdminController::class, 'activateMembership'])->name('admin.memberships.store');
    Route::delete('memberships/{membership}', [AdminController::class, 'cancelMembership'])->name('admin.memberships.cancel');
    Route::get('redemptions', [AdminController::class, 'redemptions'])->name('admin.redemptions.index');
    Route::get('attribution', [AdminController::class, 'attribution'])->name('admin.attribution.index');
    Route::post('attribution/{user}/correction', [AdminAdjustmentController::class, 'attribution'])->name('admin.attribution.correction');
    Route::put('attribution/settings', [AdminController::class, 'updateAttributionSettings'])->name('admin.attribution.settings.update');
    Route::get('sales', [AdminSalesController::class, 'index'])->name('admin.sales.index');
    Route::get('sales/create', [AdminSalesController::class, 'create'])->name('admin.sales.create');
    Route::post('sales', [AdminSalesController::class, 'store'])->middleware('throttle:20,1')->name('admin.sales.store');
    Route::get('sales/{sale}', [AdminSalesController::class, 'show'])->name('admin.sales.show');
    Route::post('sales/{sale}/refund', [AdminSalesController::class, 'refund'])->name('admin.sales.refund');
    Route::get('reward-rules', [AdminRewardRuleController::class, 'index'])->name('admin.reward-rules.index');
    Route::post('reward-rules', [AdminRewardRuleController::class, 'store'])->name('admin.reward-rules.store');
    Route::put('reward-rules/{rule}', [AdminRewardRuleController::class, 'update'])->name('admin.reward-rules.update');
    Route::get('campaigns', [AdminCampaignController::class, 'index'])->name('admin.campaigns.index');
    Route::post('campaigns', [AdminCampaignController::class, 'store'])->name('admin.campaigns.store');
    Route::put('campaigns/{campaign}', [AdminCampaignController::class, 'update'])->name('admin.campaigns.update');
    Route::get('promoters', [\App\Http\Controllers\AdminPromoterController::class, 'index'])->name('admin.promoters.index');
    Route::get('promoters/create', [\App\Http\Controllers\AdminPromoterController::class, 'create'])->name('admin.promoters.create');
    Route::post('promoters', [\App\Http\Controllers\AdminPromoterController::class, 'store'])->name('admin.promoters.store');
    Route::get('promoters/{user}', [\App\Http\Controllers\AdminPromoterController::class, 'show'])->name('admin.promoters.show');
    Route::put('promoters/{user}/enrollment', [\App\Http\Controllers\AdminPromoterController::class, 'updateEnrollment'])->name('admin.promoters.enrollment.update');
    Route::post('promoters/{user}/referral-code', [\App\Http\Controllers\AdminPromoterController::class, 'referralCode'])->name('admin.promoters.referral-code');
    Route::put('promoters/{user}/commission', [\App\Http\Controllers\AdminPromoterController::class, 'commission'])->name('admin.promoters.commission');
    Route::get('affiliates', [AdminAffiliateController::class, 'index'])->name('admin.affiliates.index');
    Route::get('affiliates/create', [AdminAffiliateController::class, 'create'])->name('admin.affiliates.create');
    Route::post('affiliates', [AdminAffiliateController::class, 'store'])->name('admin.affiliates.store');
    Route::get('affiliates/{user}', [AdminAffiliateController::class, 'show'])->name('admin.affiliates.show');
    Route::put('affiliates/{user}/enrollment', [AdminAffiliateController::class, 'updateEnrollment'])->name('admin.affiliates.enrollment.update');
    Route::post('affiliates/{user}/referral-code', [AdminAffiliateController::class, 'referralCode'])->name('admin.affiliates.referral-code');
    Route::put('affiliates/{user}/commission', [AdminAffiliateController::class, 'commission'])->name('admin.affiliates.commission');
    Route::post('affiliates/{user}/rewards/{reward}/available', [AdminAffiliateController::class, 'makeAvailable'])->name('admin.affiliates.rewards.available');
    Route::get('creators', [AdminCreatorController::class, 'index'])->name('admin.creators.index');
    Route::get('creators/create', [AdminCreatorController::class, 'create'])->name('admin.creators.create');
    Route::post('creators', [AdminCreatorController::class, 'store'])->name('admin.creators.store');
    Route::get('creators/{user}', [AdminCreatorController::class, 'show'])->name('admin.creators.show');
    Route::put('creators/{user}/enrollment', [AdminCreatorController::class, 'updateEnrollment'])->name('admin.creators.enrollment.update');
    Route::post('creators/{user}/referral-code', [AdminCreatorController::class, 'referralCode'])->name('admin.creators.referral-code');
    Route::put('creators/{user}/commission', [AdminCreatorController::class, 'commission'])->name('admin.creators.commission');
    Route::post('creators/{user}/rewards/{reward}/available', [AdminCreatorController::class, 'makeAvailable'])->name('admin.creators.rewards.available');
    Route::get('payouts', [AdminPayoutController::class, 'index'])->name('admin.payouts.index');
    Route::put('payouts/settings', [AdminPayoutController::class, 'settings'])->name('admin.payouts.settings');
    Route::get('payouts/{payout}', [AdminPayoutController::class, 'show'])->name('admin.payouts.show');
    Route::post('payouts/{payout}/paid', [AdminPayoutController::class, 'pay'])->name('admin.payouts.paid');
    Route::post('payouts/{payout}/reject', [AdminPayoutController::class, 'reject'])->name('admin.payouts.reject');
    Route::get('adjustments', [AdminAdjustmentController::class, 'index'])->name('admin.adjustments.index');
    Route::post('adjustments/ledger', [AdminAdjustmentController::class, 'ledger'])->name('admin.adjustments.ledger');
    Route::post('adjustments/rewards/{reward}/status', [AdminAdjustmentController::class, 'rewardStatus'])->name('admin.adjustments.rewards.status');
    Route::get('exports/{type}', [AdminExportController::class, 'download'])->name('admin.exports.download');
});

require __DIR__.'/settings.php';

app(PublicJourneyConfig::class)->registerRoutes();
