<?php

use App\Http\Controllers\AdminContentReviewController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ExperienceCheckInController;
use App\Http\Controllers\ExperienceReservationController;
use App\Http\Controllers\MemberProfileController;
use App\Http\Controllers\MembershipController;
use App\Http\Controllers\PartnerContentController;
use App\Http\Controllers\PartnerLoginController;
use App\Http\Controllers\PartnerPortalController;
use App\Http\Controllers\PartnerReservationController;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\RedemptionController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/', [PublicController::class, 'home'])->name('home');
Route::get('/explorar', [PublicController::class, 'explore'])->name('explore');
Route::get('/partners/{partner:slug}', [PublicController::class, 'partners'])->name('partners.show');
Route::get('/partners/{partner:slug}/whatsapp', [PublicController::class, 'partnerWhatsapp'])->name('partners.whatsapp');
Route::get('/lugares/{location:slug}', [PublicController::class, 'location'])->name('locations.show');
Route::get('/lugares/{location:slug}/mapa', [PublicController::class, 'map'])->name('locations.map');
Route::get('/lugares/{location:slug}/whatsapp', [PublicController::class, 'locationWhatsapp'])->name('locations.whatsapp');
Route::get('/beneficios', [PublicController::class, 'benefits'])->name('benefits.index');
Route::get('/beneficios/{benefit:slug}', [PublicController::class, 'benefit'])->name('benefits.show');
Route::get('/experiencias', [PublicController::class, 'experiences'])->name('experiences.index');
Route::get('/experiencias/{experience:slug}', [PublicController::class, 'experience'])->name('experiences.show');
Route::get('/experiencias/{experience:slug}/reservar', [PublicController::class, 'reserve'])->name('experiences.reserve');
Route::get('/partner/login', [PartnerLoginController::class, 'create'])->middleware('guest')->name('partner.login');
Route::post('/partner/login', [PartnerLoginController::class, 'store'])->middleware('guest')->name('partner.login.store');
Route::get('/partner/{partner:slug}/canjes/{redemption_public_id}', [RedemptionController::class, 'scan'])->middleware('signed')->name('partner.redemptions.scan');
Route::post('/partner/{partner:slug}/canjes/{redemption_public_id}', [RedemptionController::class, 'scanConfirm'])->middleware(['auth', 'verified', 'partner', 'signed'])->name('partner.redemptions.scan.confirm');
Route::get('/partner/{partner:slug}/asistencias/{reservation_public_id}', [ExperienceCheckInController::class, 'scan'])->middleware('signed')->name('partner.checkins.scan');
Route::middleware(['auth', 'verified', 'partner'])->group(function () {
    Route::get('/partner', [PartnerPortalController::class, 'index'])->name('partner.index');
    Route::get('/partner/reservas', fn (Request $request) => app(PartnerPortalController::class)->redirectToSinglePartner($request, 'partner.reservations.index'));
    Route::get('/validar', fn (Request $request) => app(PartnerPortalController::class)->redirectToSinglePartner($request, 'redemptions.validate'));
    Route::get('/partner/{partner:slug}', [PartnerPortalController::class, 'show'])->name('partner.portal.show');
    Route::get('/partner/{partner:slug}/rendimiento', [PartnerPortalController::class, 'performance'])->name('partner.performance');
    Route::get('/partner/{partner:slug}/reservas', [PartnerReservationController::class, 'index'])->name('partner.reservations.index');
    Route::post('/partner/{partner:slug}/reservas/{reservation_public_id}/{status}', [PartnerReservationController::class, 'respond'])->whereIn('status', ['confirmed', 'rejected'])->name('partner.reservations.respond');
    Route::get('/partner/{partner:slug}/asistencias', [ExperienceCheckInController::class, 'form'])->name('partner.checkins.form');
    Route::post('/partner/{partner:slug}/asistencias', [ExperienceCheckInController::class, 'find'])->middleware('throttle:20,1')->name('partner.checkins.find');
    Route::post('/partner/{partner:slug}/asistencias/{reservation_public_id}', [ExperienceCheckInController::class, 'confirm'])->name('partner.checkins.confirm');
    Route::get('/partner/{partner:slug}/validar', [RedemptionController::class, 'form'])->name('redemptions.validate');
    Route::post('/partner/{partner:slug}/validar', [RedemptionController::class, 'confirm'])->middleware('throttle:20,1');
    Route::get('/partner/{partner:slug}/promociones', [PartnerContentController::class, 'benefits'])->name('partner.benefits.index');
    Route::get('/partner/{partner:slug}/promociones/crear', [PartnerContentController::class, 'benefitForm'])->name('partner.benefits.create');
    Route::post('/partner/{partner:slug}/promociones', [PartnerContentController::class, 'saveBenefit'])->name('partner.benefits.store');
    Route::get('/partner/{partner:slug}/promociones/{benefit:slug}/editar', [PartnerContentController::class, 'benefitForm'])->name('partner.benefits.edit');
    Route::put('/partner/{partner:slug}/promociones/{benefit:slug}', [PartnerContentController::class, 'saveBenefit'])->name('partner.benefits.update');
    Route::post('/partner/{partner:slug}/promociones/{benefit:slug}/enviar', [PartnerContentController::class, 'submitBenefit'])->name('partner.benefits.submit');
    Route::get('/partner/{partner:slug}/experiencias', [PartnerContentController::class, 'experiences'])->name('partner.experiences.index');
    Route::get('/partner/{partner:slug}/experiencias/crear', [PartnerContentController::class, 'experienceForm'])->name('partner.experiences.create');
    Route::post('/partner/{partner:slug}/experiencias', [PartnerContentController::class, 'saveExperience'])->name('partner.experiences.store');
    Route::get('/partner/{partner:slug}/experiencias/{experience:slug}/editar', [PartnerContentController::class, 'experienceForm'])->name('partner.experiences.edit');
    Route::put('/partner/{partner:slug}/experiencias/{experience:slug}', [PartnerContentController::class, 'saveExperience'])->name('partner.experiences.update');
    Route::post('/partner/{partner:slug}/experiencias/{experience:slug}/sessions', [PartnerContentController::class, 'saveSession'])->name('partner.experiences.sessions.store');
    Route::put('/partner/{partner:slug}/experiencias/{experience:slug}/sessions/{session}', [PartnerContentController::class, 'updateSession'])->name('partner.experiences.sessions.update');
    Route::post('/partner/{partner:slug}/experiencias/{experience:slug}/enviar', [PartnerContentController::class, 'submitExperience'])->name('partner.experiences.submit');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('dashboard', fn () => to_route('home'))->name('dashboard');
    Route::get('mi-jakawi', [MembershipController::class, 'show'])->name('mi-jakawi');
    Route::get('perfil', [MemberProfileController::class, 'show'])->name('consumer.profile');
    Route::get('mi-jakawi/perfil', [MemberProfileController::class, 'show'])->name('member.profile.show');
    Route::put('mi-jakawi/perfil', [MemberProfileController::class, 'update'])->name('member.profile.update');
    Route::post('/experiencias/{experience:slug}/reservas', [ExperienceReservationController::class, 'store'])->name('experiences.reservations.store');
    Route::post('/reservas/{reservation:public_id}/cancelar', [ExperienceReservationController::class, 'cancel'])->name('experiences.reservations.cancel');
    Route::post('/beneficios/{benefit:slug}/canjear', [RedemptionController::class, 'start'])->name('redemptions.start');
    Route::get('/canjes/{redemption:public_id}', [RedemptionController::class, 'show'])->name('redemptions.show');
});

Route::middleware(['auth', 'verified', 'admin'])->prefix('admin')->group(function () {
    Route::get('/', [AdminController::class, 'index'])->name('admin.index');
    Route::get('review', [AdminContentReviewController::class, 'index'])->name('admin.review.index');
    Route::post('review/benefits/{benefit}', [AdminContentReviewController::class, 'benefit'])->name('admin.review.benefit');
    Route::post('review/experiences/{experience}', [AdminContentReviewController::class, 'experience'])->name('admin.review.experience');
    Route::get('partners', [AdminController::class, 'partners'])->name('admin.partners.index');
    Route::get('partners/create', [AdminController::class, 'partnerForm'])->name('admin.partners.create');
    Route::post('partners', [AdminController::class, 'savePartner'])->name('admin.partners.store');
    Route::get('partners/{partner}/edit', [AdminController::class, 'partnerForm'])->name('admin.partners.edit');
    Route::put('partners/{partner}', [AdminController::class, 'savePartner'])->name('admin.partners.update');
    Route::get('locations', [AdminController::class, 'locations'])->name('admin.locations.index');
    Route::get('locations/create', [AdminController::class, 'locationForm'])->name('admin.locations.create');
    Route::post('locations', [AdminController::class, 'saveLocation'])->name('admin.locations.store');
    Route::get('locations/{location}/edit', [AdminController::class, 'locationForm'])->name('admin.locations.edit');
    Route::put('locations/{location}', [AdminController::class, 'saveLocation'])->name('admin.locations.update');
    Route::get('benefits', [AdminController::class, 'benefits'])->name('admin.benefits.index');
    Route::get('benefits/create', [AdminController::class, 'benefitForm'])->name('admin.benefits.create');
    Route::post('benefits', [AdminController::class, 'saveBenefit'])->name('admin.benefits.store');
    Route::get('benefits/{benefit}/edit', [AdminController::class, 'benefitForm'])->name('admin.benefits.edit');
    Route::put('benefits/{benefit}', [AdminController::class, 'saveBenefit'])->name('admin.benefits.update');
    Route::get('experiences', [AdminController::class, 'experiences'])->name('admin.experiences.index');
    Route::get('experiences/create', [AdminController::class, 'experienceForm'])->name('admin.experiences.create');
    Route::post('experiences', [AdminController::class, 'saveExperience'])->name('admin.experiences.store');
    Route::get('experiences/{experience}/edit', [AdminController::class, 'experienceForm'])->name('admin.experiences.edit');
    Route::put('experiences/{experience}', [AdminController::class, 'saveExperience'])->name('admin.experiences.update');
    Route::post('experiences/{experience}/sessions', [AdminController::class, 'sessions'])->name('admin.experiences.sessions.store');
    Route::put('experiences/{experience}/sessions/{session}', [AdminController::class, 'updateSession'])->name('admin.experiences.sessions.update');
    Route::delete('experiences/{experience}/sessions/{session}', [AdminController::class, 'deleteSession'])->name('admin.experiences.sessions.destroy');
    Route::get('memberships', [AdminController::class, 'memberships'])->name('admin.memberships.index');
    Route::post('memberships', [AdminController::class, 'activateMembership'])->name('admin.memberships.store');
    Route::delete('memberships/{membership}', [AdminController::class, 'cancelMembership'])->name('admin.memberships.cancel');
    Route::get('redemptions', [AdminController::class, 'redemptions'])->name('admin.redemptions.index');
});

require __DIR__.'/settings.php';
